### ISSUE TITLE
Help Wanted - Android works / iOS not

### ISSUE THREAD

**Issue by philippsander** [NativeScript/push-plugin#104]
I uploaded my Certificates in Firebase.

I have to accept PushNotifications in my App.

But I don't receive any Push notifications on iOS.

Where do I have to put the "GoogleService-Info.plist"?

What else do I have to do?

this is my Code 
'Successfully registered for interactive push.' is printed in the console

    registerIOS() {
      console.log('registerIOS');
      let me = this,
        iosSettings = {
          senderID: apiProperties.firebase_project_id,
           badge: true,
           sound: true,
           alert: true,
           interactiveSettings: {
               actions: [{
                   identifier: 'READ_IDENTIFIER',
                   title: 'Read',
                   activationMode: "foreground",
                   destructive: false,
                   authenticationRequired: true
               }, {
                   identifier: 'CANCEL_IDENTIFIER',
                   title: 'Cancel',
                   activationMode: "foreground",
                   destructive: true,
                   authenticationRequired: true
               }],
               categories: [{
                   identifier: 'READ_CATEGORY',
                   actionsForDefaultContext: ['READ_IDENTIFIER', 'CANCEL_IDENTIFIER'],
                   actionsForMinimalContext: ['READ_IDENTIFIER', 'CANCEL_IDENTIFIER']
               }]
           },
           notificationCallbackIOS: function (data) {
             console.log('notificationCallbackIOS');
              console.dump(data);
              me.handlePushClick(data);
           }
       };

       PushPlugin.register(iosSettings, function (data) {
         console.log('PushPlugin.register IOS');
           console.dump(data);

           me.sendRegisterToApi(data, 'APNS');

           // Register the interactive settings
               if(iosSettings.interactiveSettings) {
                   PushPlugin.registerUserNotificationSettings(function() {
                       console.log('Successfully registered for interactive push.');
                   }, function(err) {
                       console.log('Error registering for interactive push: ' + JSON.stringify(err));
                   });
               }
       }, function() {console.log('callback?') });
    }

**Comment by AntonDobrev** [comment]
@philippsander As discussed in #95 the plugin utilizes FCM only for the Android part (because it is required for being able to send and receive push messages for Android). As for the iOS part, you need to save the device token on your preferred provider and send messages to it directly via APNs. 

You cannot use Firebase to send push messages to iOS with this plugin. 

For example, you can utilize a service like Telerik Platform or another to manage the device registrations and send push messages to iOS. 

Let me know if this answers your question.

**Comment by philippsander** [comment]
wow....

that's disapointing... you should mention that in the documentation!
