### ISSUE TITLE
onTokenRefresh callback has no argument

### ISSUE THREAD

**Issue by philippsander** [NativeScript/push-plugin#106]
Readme says:

`pushPlugin.onTokenRefresh(function(token){
            alert(token);
        });`

definitions.d.ts says:

`export declare function onTokenRefresh(callback: () => void): void;`

I'd expect a token.

**Comment by AntonDobrev** [comment]
@philippsander 

Thanks for your report. The documentation, unfortunately, is not correct here. The callback will be called w/o arguments. 

In your app in the event handler you can register again for push, which will fetch the new token or use some native code to get the token from the service.

However, I also think that the token should be received in the callback or at least the behavior should be documented correctly. 

I am sorry for this discrepancy.

**Comment by lini** [comment]
Documentation is updated.
