### ISSUE TITLE
How to build this plugin locally on a Mac to generate new Android library?

### ISSUE THREAD

**Issue by svzi** [NativeScript/push-plugin#108]
#Hi there!

I needed to fork this repository (compare with https://github.com/NativeScript/push-plugin/pull/107) and made some changes to the source code. 

It was easy to do the necessary adjustments on the Java side, but I'm unable to build a new .aar file from my local version of the plugin. I opened the `native-src/android` folder with intelliJ IDE. After configuring the correct `AndroidManifest.xml` I was able build the project, but I have no idea on how to generate/export the library (`platforms/android/libs/app-release.aar`).

I would really appreciate some kind of step-by-step guide on how to build this plugin locally (including the export of the .aar file). Could you please provide it?

Best,
Sven

**Comment by svzi** [comment]
> I have an idea, navigate to `push-plugin/native-src/android/` and run `gradlew assembleRelease`, see if that work for you

That solved my issue, thanks a lot, @Pip3r4o !

**Comment by JCBsystem** [comment]
@svzi can you please share exact how to build and install the new plugin 
thanks

**Comment by svzi** [comment]
I'm sorry @JCBsystem, but I can't recall that. Too long ago. I posted my solution in the second comment. Didn't that work for you?

**Comment by Pip3r4o** [comment]
@JCBsystem building the Android aar should be as simple as navigating to https://github.com/NativeScript/push-plugin/tree/master/native-src/android and running `./gradlew assembleRelease` or `gradlew assembleRelease` on Windows.
