### ISSUE TITLE
App has stopped

### ISSUE THREAD

**Issue by NikitaKurdin** [NativeScript/push-plugin#116]
When plugin is added to a project I have received this message when trying emulate an android device.
Sreenshot: http://joxi.ru/Vm63BbqCD7p132

If I remove the plugin - the app is ok.

**Comment by AntonDobrev** [comment]
@NikitaKurdin Please check the stacktrace logged from the android application it will contain the exception message that caused the crash and this will help to resolve the issue. 

My feeling is that you need to configure the plugin as explained in the docs. First it is best to run _tns platform remove android_, then add the platform again, add and configure the plugin.
