### ISSUE TITLE
Question: amazon SNS

### ISSUE THREAD

**Issue by tigrenok00** [NativeScript/push-plugin#120]
Hi,
Can this be configured to work with other providers, like amazon SNS? Or is it designed for Firebase only?
Thanks!

**Comment by NickIliev** [comment]
@tigrenok00 the plugin works with [Firebase ](https://github.com/NativeScript/push-plugin#android-configuration-for-using-firebase-cloud-messaging)and with [Telerik  Everlive](https://github.com/NativeScript/sample-push-plugin). If you need a solution for using amazon services in a NativeScript application then you can try [nativescript-nodeify](https://github.com/EddyVerbruggen/nativescript-nodeify) and follow the instructions in the aws-sdk section.
