### ISSUE TITLE
InvalidRegistration for iOS

### ISSUE THREAD

**Issue by loadchief** [NativeScript/push-plugin#122]
a registration id is being generated using plugin but when using rest api for FCM in postman we get this error below:

```
{
  "multicast_id": 6627788995350625388,
  "success": 0,
  "failure": 1,
  "canonical_ids": 0,
  "results": [
    {
      "error": "InvalidRegistration"
    }
  ]
}
```

we generated APN auth key per firebase docs, uploaded it to firebase, we also tried to send a push notification from firebase which never arrives on device.  We are not having any issues on Android.

nativescript 2.5.4
iOS 10.3.2
xcode 8.3.2
ios actual device

cc @nraboy

**Comment by nraboy** [comment]
I'm wondering, and this is because it isn't obvious in the README, does this plugin only use FCM for Android? The README doesn't talk about iOS and FCM so I'm wondering if it even uses it.

If not, what do we do?

**Comment by AntonDobrev** [comment]
@loadchief @nraboy In brief, yes, the plugin is using pure APNs communication protocol provided by the respective framework in the iOS SDK. It does not use the Firebase SDK for iOS. I agree this is not well documented and will correct this in a while. 

This is a design decision made with the purpose to make the plugin independent from a backend implementation (not all developers are using Firebase directly) and cater to push backend infrastructures communicating with APNs for iOS and FCM (formerly GCM) for Android. 

If you definitely need the iOS push notifications to be powered by Firebase, you may need to use the {N} Firebase plugin from [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase).

To continue using this plugin you may consider one of the large portion of push notifications providers out there or an own server and send the APNs token there. 

Let me know if this answers your question and if I may be of further assistance.

**Comment by loadchief** [comment]
Hi Anton, I am able to register my iphone with the push plugin and get back an apn token.  Then I was able to exchange that apn token for an fcm token.  But then when I try to send a test push thru postman (with the exchanged token) I get back:    "error": "InvalidRegistration"

**Comment by loadchief** [comment]
```
{
	"notification": {
		"title": "test ios push",
		"body": "ios message body"
	},
	"content_available": true,
	"priority": "high",
	"to": "dxwMIPuinOI:APA91bGEas67YXCWmV1ChsefhOWLjnSO-rjvCBFdQEHKxEHmrXqjdz6D-e-F72bNDGgSp5qrkDHXFautvCztCqvXgPld0QSIzfFNEo8gndzCB9E6uiUMLyf_B_JMxxxxxxxxxx"
	
}
```

**Comment by AntonDobrev** [comment]
@loadchief 

Good to know that you successfully exchanged the tokens, this sounds like a valid approach for your case. 

This error mainly signifies (from what I have seen in the past) that the Firebase token is not valid. One usual reason for this is that the token was issued for another project (check the app id for which you registered these tokens and API key). 

I'd also suggest that you double check all prerequisites for the exchange, and also, check if the iOS token is valid by calling directly APNs (just as a good measure, though the plugin registration will return a valid token from APNs).

**Comment by nraboy** [comment]
Just following up with a tutorial in case you need a bit more information:

https://www.thepolyglotdeveloper.com/2017/06/apns-tokens-fcm-tokens-simple-http/
