### ISSUE TITLE
Compatible with nativescript version 3.0?

### ISSUE THREAD

**Issue by magar91** [NativeScript/push-plugin#124]
I updated nativescript to version 3.0 and when i try to run my app I get this error:

```terminal
> Failed to apply plugin [id 'com.google.gms.google-services']
   > For input string: "+"
```

**Comment by NickIliev** [comment]
@magar91 can you post the content of your `package.json`

**Comment by magar91** [comment]
this is my `package.json` @NickIliev 
```json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.smartcities",
    "tns-android": {
      "version": "3.0.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "angular2-jwt": "^0.2.3",
    "email-validator": "^1.0.7",
    "nativescript-angular": "~3.0.0",
    "nativescript-audio": "^3.4.2",
    "nativescript-camera": "^3.0.0",
    "nativescript-checkbox": "^2.0.0",
    "nativescript-drop-down": "^3.0.1",
    "nativescript-geolocation": "^3.0.0",
    "nativescript-google-maps-sdk": "^2.0.3",
    "nativescript-i18n": "^0.2.1",
    "nativescript-imagepicker": "^3.0.1",
    "nativescript-oauth": "^2.0.0",
    "nativescript-push-notifications": "^0.1.3",
    "nativescript-ripple": "^1.1.0",
    "nativescript-telerik-ui": "^2.0.1",
    "nativescript-theme-core": "~1.0.2",
    "nativescript-toast": "^1.4.5",
    "nativescript-vibrate": "^1.1.2",
    "nativescript-web-image-cache": "^4.1.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "~3.0.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.24.1",
    "babel-types": "6.24.1",
    "babylon": "6.17.1",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.2.1"
  }
}
```

**Comment by AntonDobrev** [comment]
@magar91 The latest version is NS 3.0 compatible. Please double check the plugin instructions for Android in the README of this repo. You may need to check whether you have removed and again added the Android platform (_tns platform remove android_ and _tns platform add android_). A similar issues was discussed [here](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/163). 

Hope this helps.

**Comment by NickIliev** [comment]
@magar91 Ithe reason behind this issue is most likely conflict within the version of google-play-services which **nativescript-google-maps-sdk** and **nativescript-push-notifications** are trying to use.
To overcome this problem run **npm install** (remove **node_modules** and **platforms** before that)
and then navigate to **_node_modules/nativescript-google-maps-sdk/platforms/android/include.gradle_** and change this line:
```
	def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : '+'
```
to this
```
	def googlePlayServicesVersion = project.hasProperty('googlePlayServicesVersion') ? project.googlePlayServicesVersion : '10.0.1'
```

Note that the version you are setting here depends on the version used in the 
 **_node_modules/nativescript-push-notifications/platforms/android/include.gradle_** set for
```
compile 'com.google.firebase:firebase-messaging:10.0.1'
```

Or use [this workaround](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/163#issuecomment-289934477) (pretty much the same idea)

**Comment by briandilley** [comment]
Adding the following to app/App_Resources/Android/app.gradle works too:
    ext {
      googlePlayServicesVersion = '10.0.1'
    }
I find this to be more elegant as I don't like messing with stuff under `platforms`.
