### ISSUE TITLE
Android error build

### ISSUE THREAD

**Issue by Sevensnake** [NativeScript/push-plugin#130]
error I keep receiving.

## FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':processF0F1DebugGoogleServices'.
> No matching client found for package name 'com.nativescript.domain'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.064 secs
Command ./gradlew failed with exit code 1
# build android ##

**Comment by mounirka** [comment]
Have you got installed android studio? Have you updated all the repositories from android studio?
