### ISSUE TITLE
iOS + Google FCM

### ISSUE THREAD

**Issue by nonzod** [NativeScript/push-plugin#133]
Hi,
I tried to follow the instructions in the [following link](http://developer.telerik.com/products/nativescript/use-firebase-cloud-messaging-nativescript-app/).

On android works well, but iOS does not receive the token or notifications.
The instructions in that link are still valid?

**Comment by nernsting** [comment]
Same issue here. Notifications are allowed and the callback function isn't reached.

**Comment by simonox** [comment]
Also in my setup.

```
pushPlugin.register(iosSettings, (token) => {
   console.log('TOKEN', token);
}
````

The callback is never called.

**Comment by AntonDobrev** [comment]
Thanks for the feedback. 

As far as I can see the article is valid - please note the small comment under the post. More information at this [link](https://www.thepolyglotdeveloper.com/2017/06/apns-tokens-fcm-tokens-simple-http/) and #122 .
I hope this helps.

**Comment by simonox** [comment]
The Capability is not enabled. You can enable them during the build process using the nativescript-custom-entitlements plugin.

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
```

**Comment by NickIliev** [comment]
@nonzod  @simonox the latest version of push-plugin is not reproducing the issue and all notifications are received on iOS (use the demo with own FCM settings for testing purposes).

Closing this one but please let me know if you are still experiencing troubles with FCM on iOS.
