### ISSUE TITLE
Cannot retrieve data from data json object

### ISSUE THREAD

**Issue by inmra858** [NativeScript/push-plugin#136]
I am using Data Messages in my nativescript angular app but in the method  notificationCallbackAndroid i cannot get my data for example data.title return undefined although the key title and his value exist in data object
Any ideas plz ??!!

**Comment by SamuelGRwebfab** [comment]
`pushPlugin.onMessageReceived(function callback(message, data, notification) {
            
            
            let dataObj = JSON.parse(data)
});`
