### ISSUE TITLE
Push Notification entitlement is removed from entitlement file when tns run ios --device XXXXX

### ISSUE THREAD

**Issue by ickata** [NativeScript/push-plugin#138]
Hi,

If I want to debug on a real device, it cannot register for push notifications because Push Notification entitlement is removed from entitlement file.

## To reproduce:

```
rm -rf platforms node_modules hooks
tns platform add ios
tns build ios
```

After the build open the .xcworkspace file in XCode and enable Push Notifications capability. Everything looks OK. Then:

```
tns run ios --emulator
tns run ios --device XXXXXXXXXXX
```

This results in app not being able to register for Push Notifications. When I open XCode, I get this: https://drive.google.com/open?id=0B2AhxJT346D-RDI2X0pjR044Rmc

{N} version 3.1.1 
Push plugin version 0.1.4

**Comment by charalamposc** [comment]
I have experienced α similar problem. Perhaps its not something that everyone can reproduce, but it can help you understand better the problem.

If you are using the [nativescript push notification plugin](https://github.com/NativeScript/push-plugin) you need to place a file called `[project name].entitlements` in the `App_Resources/iOS` folder. In this file you need to have the following content (in case you are developing):

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>aps-environment</key>
	<string>development</string>
</dict>
</plist>
```

So, if you run `tns build ios` and open the xcode project (I have version 9.0), then you will find this file under the folder `/Resources`. 

Perhaps you need to turn on the push notification service under the tab Capabilities.

But it seems that xcode can't read or find the file in this location. So, it creates a new one under the folder `/[project name]`, in the same level as `/Resources`. If you check with Finder (xcode don't show me the files in this folder) under this folder you will find such a file `[project name].entitlements`, only the content will look like:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict/>
</plist>
```

even if xcode is telling you that it has placed the correct entitlement strings in the file.

So, if you edit this file, and change the content like above, and run the project from xcode, then it will be fine.

**Comment by ickata** [comment]
@charalamposc ,

Thanks for the workaround!

I'll summarise the steps in case someone has the same problem:

1. Run `rm -rf platforms/ios`
2. Run `tns build ios`
3. Paste the file contents **charalamposc** posted above inside `platforms/ios/<project_name>/<project_name>.entitlements` (in my case it was `platforms/ios/mobile/mobile.entitlements`)
4. Run `tns run ios --device XXXXXXXXXXX`

Closing this one, as there is relatively simple workaround.
