### ISSUE TITLE
Background Notifications Are Not Received on Android Oreo

### ISSUE THREAD

**Issue by spstratis** [NativeScript/push-plugin#141]
Does the plugin currently support Android Oreo? 

On all versions of Android prior to Oreo I'm able to receive background notifications. Once I began testing on a Nexus 5X running Oreo, The notification call back is only fired off when the application is in the foreground. I have verified that Token registration with GCM is working and that I'm retrieving the token on the device. 

I'm using version 0.0.19 of the plugin since I'm not yet able to move over to FCM.

**Comment by tayyabaAslam** [comment]
@spstratis were you able to fix this?

**Comment by NickIliev** [comment]
Confirming this as a bug - steps to reproduce use [this demo application ](https://github.com/NativeScript/push-plugin/tree/lini/add-demo-apps/demo)on Android 8.0 (Oreo)

**Comment by NickIliev** [comment]
+1 reported via t. 1142590

**Comment by spstratis** [comment]
@tayyabaAslam  I was only able to get background notifications working by targeting a lower version of the Android API in my manifest file.

**Comment by tayyabaAslam** [comment]
@spstratis I have used 25 as my target sdk version. I am getting the background notification on Oreo but there is no icon showing now. Any idea?

**Comment by gregersen79** [comment]
Any workaround or fix for this? I'm also not receiving notification on Android Oreo (tested on Google Pixel 2 Android 8.1.0). Tried targeting sdk 25 and 26 but no luck.

**Comment by gregersen79** [comment]
Facing same issue. Notifications not received with sdk version 26, lower sdk version to 25 works.

**Comment by lini** [comment]
Please update to the latest version of the plugin (v0.20.0) and see if the Android Oreo issues are resolved.
https://github.com/NativeScript/push-plugin/releases/tag/v0.20.0
