### ISSUE TITLE
[Android] areNotificationsEnabled does not return boolean value

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/push-plugin#143]
On android in the callback for `areNotificationsEnabled` the value returned is the string representation  of the boolean value and not the boolean value itself. This is inconsistent with the value that is returned under iOS and causes app crashes if you use this value for `isEnabled` binding of some control(s).

**Comment by PeterStaev** [comment]
Actually I do  not know what type it is but it is neither string nor boolean. on an Android API25 emulator the following are the results
```ts
        pushPlugin.areNotificationsEnabled((result) => {
            console.log(result); // true
            console.log(result === true); // false
            console.log(result === "true"); // false
            console.log(result.toString() === "true"); // true

        });
```

**Comment by lini** [comment]
The function is intended to work in Android - the native code simply returns true:
https://github.com/NativeScript/push-plugin/blob/34891832f01c3e7201f884fc9f9ca1cec196c65e/native-src/android/app/src/main/java/com/telerik/pushplugin/PushPlugin.java#L162

The value you get in JavaScript is the native [java.lang.Boolean](https://docs.oracle.com/javase/7/docs/api/java/lang/Boolean.html) object. You can either ignore it, call `result.booleanValue()` to get the real value on Android, or simply do `!!result` to always convert it to true/false in both Android/iOS.

**Comment by PeterStaev** [comment]
@lini , this is wrong. Considering this is a cross platform plugin it does not make sense to have the iOS side return a true JS boolean and the Android side to return a `java.lang.Boolean` value (even though it always returns `true` . The value should be coded the same way for both platforms and should not require additional hacks like `!!` or checks to check if the plugin is being used in Android or iOS. 

So I think you should reopen this and make the Android wrapper do the transformation here:
https://github.com/NativeScript/push-plugin/blob/b153db7f4cb74e590822efa2e549eb84910f0e48/src/push-plugin.android.ts#L68-L71

**Comment by lini** [comment]
I did some research and it seems the primitive type boolean in Java is perfectly suited and translates to a normal boolean value in JavaScript. I will make a PR to fix the native code now.
