### ISSUE TITLE
Unable to receive notification when firebase plugin is installed

### ISSUE THREAD

**Issue by manishbaruah** [NativeScript/push-plugin#147]
Hi,

Is there any way where I can get this plugin work together with firebase plugin? The problem I am facing is tough I am able to built my project, I am not receiving the push notifications if I use the nativescript-plugin-firebase plugin installed. Without the plugin the notifications are showing up fine.

**Comment by lini** [comment]
The firebase plugin has it's own FCM push notifications implementation. You should try using it instead of this plugin.
