### ISSUE TITLE
Android not receiving background notifications (when app is killed/ not started)

### ISSUE THREAD

**Issue by cutout33** [NativeScript/push-plugin#150]
Hi,

I just installed this plugin and am trying to send msgs from firebase console. and am getting the following behavior:

1. if i register `pushPlugin.onMessageReceived` I get no msgs at all and I get this error:

>
> System.err: org.json.JSONException: No value for message
> System.err: 	at org.json.JSONObject.get(JSONObject.java:389)
> System.err: 	at org.json.JSONObject.getString(JSONObject.java:550)
> System.err: 	at com.telerik.pushplugin.PushPlugin.executeOnMessageReceivedCallback(PushPlugin.java:105)
> System.err: 	at com.telerik.pushplugin.PushPlugin.executeOnMessageReceivedCallback(PushPlugin.java:81)
> System.err: 	at com.telerik.pushplugin.PushPlugin.onMessageReceived(PushPlugin.java:131)
> System.err: 	at com.google.firebase.messaging.FirebaseMessagingService.zzo(Unknown Source)
> System.err: 	at com.google.firebase.messaging.FirebaseMessagingService.zzn(Unknown Source)
> System.err: 	at com.google.firebase.messaging.FirebaseMessagingService.zzm(Unknown Source)
> System.err: 	at com.google.firebase.iid.zzb$2.run(Unknown Source)
> System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
> System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
> System.err: 	at java.lang.Thread.run(Thread.java:833)
> 

So I had to remove it!

2. If the app is opened the message is received with no content!
3. If the I get out of the app (with out killing it) I receive message without ringtone!
4. If I lock the phone I stop receiving the messages :/

Can someone guide to what is going on and how to get this up and running?

Thanks in advance!

**Comment by NickIliev** [comment]
Reproduced on Android [with this application](https://github.com/NativeScript/push-plugin/tree/lini/add-demo-apps/demo)

**Comment by lini** [comment]
Should be fixed in v0.20.0
https://github.com/NativeScript/push-plugin/releases/tag/v0.20.0
