### ISSUE TITLE
 What does IOS interactiveSettings mean

### ISSUE THREAD

**Issue by seohangyu** [NativeScript/push-plugin#153]
I'm implementing push alarm for the first time.
I want to know what the setting of 'interactiveSettings' means.
 And I wonder what the badge means.

![2017-12-12 6 48 48](https://user-images.githubusercontent.com/23069763/33877919-40978ad0-df6d-11e7-9274-ebad8714daa2.png)

**Comment by lini** [comment]
The badge is the little number you see over the application icon on the iOS home screen:
![](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Art/badged_app_2x.png)

The interactive settings are meant to provide a way for the user to take some kind of action directly from the notification itself, without having to open the app. For example - your app might send a notification with an invitation to join a group. With interactive notifications, the user can accept/reject the invitation with two buttons in the notification itself.

For more information, visit the Apple Developer site: https://developer.apple.com/notifications/

**Comment by seohangyu** [comment]
@lini  thank you!
