### ISSUE TITLE
Android notifications icon not showing oreo.

### ISSUE THREAD

**Issue by haris008** [NativeScript/push-plugin#155]
We are using icon with transparent background. it is showing in lollipop devices, but not showing in oreo. It is showing as gray box

This is how we are showing

`<meta-data android:name="com.google.firebase.messaging.default_notification_icon" 
			android:resource="@drawable/android_icon" />`

'andriod_icon' is where icon name which we want to show.
android:targetSdkVersion="21"

**Comment by gregersen79** [comment]
Same here, notification icon is just a gray box.

**Comment by lini** [comment]
We just published a new version of the nativescript-push-notifications plugin, which features fixes for Android Oreo. Please test your app with it and see if the issues you experience are gone. Note that the new version has a breaking change in the Android onMessageReceived callback.
 https://github.com/NativeScript/push-plugin/releases/tag/v0.20.0
