### ISSUE TITLE
Android 7.1.1 "Nougat" does not receive notification

### ISSUE THREAD

**Issue by ickata** [NativeScript/push-plugin#161]
Notifications are not received in tray.

Reproducing issue on Android emulator using plugin version 0.2.0.

**Cannot reproduce** on the same emulator with plugin version 0.1.5.

Haven't tested with other Android versions.

**Comment by lini** [comment]
I tested this scenario on an emulator running API 25 (7.1.1 Nougat) and was able to receive notifications while the app is not in the foreground with version 0.2.0. I am using the demo app in the push plugin repository to test this:
![image](https://user-images.githubusercontent.com/1461621/34522900-a43cb22c-f09d-11e7-9e9a-5db87f48d0de.png)

**Comment by ickata** [comment]
I was using plugin version 0.1.5 . With this version my notification payload looked like this:

```
   {
      to    : "device_token",
      data  : {
         "custom_key": "value",
         title       : "title",
         message     : "message",
         smallIcon   : 'icon_notify',  // defined in App_Resources
         sound       : 'notify',       // defined in App_Resources
      },
   }
```

Plugin version 0.1.5 handled this as a "mixed" notification + data message, displaying notification icon + message in the tray. With recent plugin version the above does not work anymore, I have to change it to this:

```
   {
      to    : "device_token",
      data  : {
         "custom_key": "value",
      },
      notification : {
         title       : "title",
         body     : "message",
         smallIcon   : 'icon_notify',  // defined in App_Resources
         sound       : 'notify',       // defined in App_Resources
      },
   }
```

But this way I'm having issues with notification icon and custom sound. I'd better create separate issue for these problems.
