### ISSUE TITLE
 The ios push alarm does not arrive. Do I have to install 'Fcm sdk'?

### ISSUE THREAD

**Issue by seohangyu** [NativeScript/push-plugin#164]
what`s the problem?

push.register has been well applied (code)

IOS apns setting is perfect

1. xcode provisioning file apply

2. capabilities - push notifications on 

3. and setup app on my ios phone.

pushalarm -> ok 

console.firebase.com --> message send  -> but not arrive

**Comment by lini** [comment]
Are you trying to send push notifications from firebase console to iOS devices? The push plugin does not support this scenario at the moment - Firebase is only available on Android devices and APNs is only available on iOS.
