### ISSUE TITLE
Gradle fails with tns-android@3.4.0

### ISSUE THREAD

**Issue by tom95** [NativeScript/push-plugin#165]
When using at the most recent version, currently android@3.4.0, gradle fails with the following log:
```
$ tns build android
Executing before-prepare hook from /home/tom/Code/js/gz-native/hooks/before-prepare/nativescript-dev-typescript.js
Found peer TypeScript 2.4.2
Executing before-prepare hook from /home/tom/Code/js/gz-native/hooks/before-prepare/nativescript-push-notifications.js
Preparing project...
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-push-notifications for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (android)
Building project...
Gradle build...

FAILURE: Build failed with an exception.

* Where:
Build file '/home/tom/Code/js/gz-native/platforms/android/build.gradle' line: 11

* What went wrong:
Could not compile build file '/home/tom/Code/js/gz-native/platforms/android/build.gradle'.
> startup failed:
  build file '/home/tom/Code/js/gz-native/platforms/android/build.gradle': 11: expecting anything but ''\n''; got it anyway @ line 11, column 51.
     roid.tools.build:gradle:2.3.3'
                                   ^  
  1 error

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
Command ./gradlew failed with exit code 1
```

Indeed, the added classpath in the build.gradle did start with double quotes and is terminated with single quotes. After fixing this manually new problems arise about missing targets, which led me to believe that some of the regex magic used to update the gradle file might have broken.

Trying the same commands to add the plugin on the version of tns-android used in the demo, 3.3.1, yields no problems.

**Comment by skhye05** [comment]
I am having the same issue.

**Comment by chiquitto** [comment]
I am having the same issue.

**Comment by SamuelReeder** [comment]
Same here. Heres hoping it get fixed soon

**Comment by SamuelReeder** [comment]
the update also breaks webpack builds :/

**Comment by tom95** [comment]
For anyone looking for a fast/temporary fix: I was able to replace the push-plugin with little effort via the https://github.com/EddyVerbruggen/nativescript-plugin-firebase plugin, see specifically https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md. (only tried it on android thus far)

**Comment by SamuelReeder** [comment]
This would would for sure but it also comes with a bunch of stuff i dont want slowing down the launch of my app :/

**Comment by tom95** [comment]
FCM is the preferred way to handle things now, see https://developers.google.com/cloud-messaging/faq I'm not sure what the push-plugin uses under the hood. My personal recommendation would be to go with the fastest way to get things working in a stable way and then see if optimization is actually required.

**Comment by SamuelReeder** [comment]
I have used the firebase plugin in the past and it does add in a fair amount of load time. if this app is not updated soon however, I will be foreced to switch

**Comment by mshanak** [comment]
To work around this problem : 

After installing the plugin, and **Before** running the application, remove the **platforms, hooks** folders.

Then edit the following file:
`node_modules/nativescript-push-notifications/hooks/utils.js  line 121
`
 replace the line 
`result += buildGradleContents.substring(ind + ('classpath "' + androidGradle).length);
`
with the following 
` result += buildGradleContents.substring(ind + ('classpath \'' + androidGradle).length);
`
finally can run the application normally .
Note: The edits will be lost in case you reinstalled the plugin or when the node_modules folder remove.

**Comment by lini** [comment]
This issue should be fixed in the latest release - https://github.com/NativeScript/push-plugin/releases/tag/v0.3.0
