### ISSUE TITLE
Not receiving push notifications

### ISSUE THREAD

**Issue by madsongr** [NativeScript/push-plugin#166]
I'm sending push notifications with php script but I cannot receive them. I can register and get my token from fcm with success.

This is the payload result with success:

`Result: {"multicast_id":5775932825803865467,"success":1,"failure":0,"canonical_ids":0,"results":[{"message_id":"0:1514317072210466%e17bdb85f9fd7ecd"}]}`

payload:

```
<?php

include_once("conn.php");

$sql = mysqli_query($mysqli, "SELECT token FROM tokens");

$registration_IDs = array();

while($row = mysqli_fetch_array($sql)){
	
	$registration_IDs[] = $row['token'];

}

$to = $registration_IDs;
var_dump($to);
echo '<br><br>';

// $title = "$get_title";
// $message = "$get_message";

$title = "Title";
$message = "Push notifications message";

sendPush($to,$title,$message);

function sendPush($to,$title,$message) {
// API access key from Google API's Console
// replace API
define( 'API_ACCESS_KEY', '*****************************************');
$registrationIds = $to;
$msg = array (
	'message' => $message,
	'title' => $title

// you can also add images, additionalData
);

$fields = array (
	'registration_ids' => $registrationIds,
	'data' => $msg
);

$headers = array (
	'Authorization: key=' . API_ACCESS_KEY,
	'Content-Type: application/json'
);

	$ch = curl_init();
	curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
	curl_setopt( $ch,CURLOPT_POST, true );
	curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
	curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
	curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
	curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
	$result = curl_exec($ch );
	curl_close( $ch );
	echo "Result: ". $result . "<br><br>";

}

?>
```
home-view-model.ts:

```
import { Observable } from "data/observable";

import * as pushPlugin from "nativescript-push-notifications";

export class HomeViewModel extends Observable {

    private pushSettings = {
        // Android settings
        senderID: "*****************", // Android: Required setting with the sender/project number
        notificationCallbackAndroid: (stringifiedData: String, fcmNotification: any) => {
            const notificationBody = fcmNotification && fcmNotification.getBody();
            this.updateMessage("Message received!\n" + notificationBody + "\n" + stringifiedData);
        },

        // iOS settings
        badge: true, // Enable setting badge through Push Notification
        sound: true, // Enable playing a sound
        alert: true, // Enable creating a alert
        notificationCallbackIOS: (message: any) => {
            this.updateMessage("Message received!\n" + JSON.stringify(message));
        }
    };

    private _counter: number;
    private _message: string;

    constructor() {
        super();
        this.message = "";
        this.updateMessage("App started.");

        let self = this;
        this.onRegisterButtonTap();
    }

    get message(): string {
        return this._message;
    }

    set message(value: string) {
        if (this._message !== value) {
            this._message = value;
            this.notifyPropertyChange("message", value);
        }
    }

    onCheckButtonTap() {
        let self = this;
        pushPlugin.areNotificationsEnabled((areEnabled: Boolean) => {
            self.updateMessage("Are Notifications enabled: " + !!areEnabled);
        });
    }

    onRegisterButtonTap() {
        let self = this;
        pushPlugin.register(this.pushSettings, (token: String) => {
            self.updateMessage("Device registered. Access token: " + token);
            // token displayed in console for easier copying and debugging durng development
            console.log("Device registered. Access token: " + token);

            if (pushPlugin.onMessageReceived) {
                pushPlugin.onMessageReceived(this.pushSettings.notificationCallbackAndroid);
            }

            if (pushPlugin.registerUserNotificationSettings) {
                pushPlugin.registerUserNotificationSettings(() => {
                    self.updateMessage("Successfully registered for interactive push.");
                }, (err) => {
                    self.updateMessage("Error registering for interactive push: " + JSON.stringify(err));
                });
            }
        }, (errorMessage: String) => {
            self.updateMessage(JSON.stringify(errorMessage));
        });
    }

    onUnregisterButtonTap() {
        let self = this;
        pushPlugin.unregister(
            (successMessage: String) => {
                self.updateMessage(successMessage);
            },
            (errorMessage: String) => {
                self.updateMessage(JSON.stringify(errorMessage));
            },
            this.pushSettings
        );
    }

    private updateMessage(text: String) {
        this.message += text + "\n";
    }

}

```

**Comment by lini** [comment]
Try sending a notification from the Firebase console https://console.firebase.google.com/
Set the target to be the whole app like below and see if the notifications are received then:
![image](https://user-images.githubusercontent.com/1461621/34521647-8096e726-f097-11e7-8251-8c9cf00a8104.png)

This way you can pinpoint the source of the problem - if the notification is received then you have to check your PHP script or the tokens used to target the specific devices. If the notification is not received, make sure there is no network firewall blocking the delivery on the device. Then check if the senderID in the push plugin configuration matches the sender ID in the Cloud Messaging settings in the Firebase console. Finally, check if you are using a recent version of the push plugin - version 0.2.0+ includes a some fixes Oreo devices that were not receiving notifications.

**Comment by madsongr** [comment]
Ok, I can receive it from firebase console. But I really don't know what's wrong. PHP script is correct because it returns success: 1 and sender_id is the same as fcm.

**Comment by lini** [comment]
You should debug the script and find out exactly what headers and body it is sending. You can also try to send from the console using curl and compare the requests:


    curl -X POST --header "Authorization: key=<SERVER_KEY_FROM_CLOUD_MESSAGING_SETTINGS_IN_FIREBASE_CONSOLE>" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"badge\": \"1\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"<FCM_REGISTRATION_TOKEN_OF_DEVICE\"}"

**Comment by madsongr** [comment]
@lini I pasted your curl code in linux console changing the credentials but nothing happens after pressing enter. It shows me a new line with >

**Comment by lini** [comment]
That's strange. The above command works in my console. For example:

curl -X POST --header "Authorization: key=AAAAAA" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"badge\": \"1\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"BBBBBB\"}"

where AAAAAA is my server key and BBBBBB is the device registration token.

Make sure that you replace them correctly in the command - a new line starting with > indicates that you probably left a \ somewhere or replaced more than you should have.

**Comment by madsongr** [comment]
This one worked but gave me this error:

```
JSON_PARSING_ERROR: Unexpected character (n) at position 1.
curl: (3) Port number ended with ' '
curl: (3) [globbing] unmatched close brace/bracket in column 31
```

If I set "key" and "to" between <> it shows me: 

`bash: kOpmmaOIjlakmcGNWjQPMPzw:APA91bEfaTYF8mUZret4SN8UVoDa2YUdNxgEdwu-iABAGrxr9wijwENDZ0VVkbVWl1faeJvs7SIOwPZoyIKQvagNkGc9-qSS9LRFZfv: File or directory not found`

**Comment by lini** [comment]
Github seems to be removing the backslashes used to escape the strings in the notification content of the command. Please use the Gist provided https://gist.github.com/lini/688ce4f0f7dfc0dd7d061939f69fedcd with the correct code.

**Comment by madsongr** [comment]
Now it worked! But still not receiving notifications even with "success":1

**Comment by madsongr** [comment]
I made some tests and working with push-plugin or firebase plugin the notification is received (I can get the log in console) but not displayed in android shade. 

Sending with google's firebase console or curl x post:
- notification is only displayed in shade in background mode;

Sending with php script:
- notification is NOT displayed in shade even in background or foreground mode (I only can see the result in console.log);

**Comment by Sheikh-Alvee** [comment]
We are facing same issue, from firebase its working but on base of curl request is not working
