### ISSUE TITLE
Android issue - Restart the app on Notification tray item click

### ISSUE THREAD

**Issue by prabudevarrajan1** [NativeScript/push-plugin#177]
In android, while the app is running in background on click of notification from Android Notification Tray restarts the app from beginning instead of just resuming the app.

**Comment by tomylee001001** [comment]
you need to set launchMode in /app/App_Resources/Android/AndroidManifest.xml file's main activity like android:launchMode="singleTop".

**Comment by prabudevarrajan1** [comment]
Yes, I have set launchMode in AndroidManifest.xml, but still the app restarts from beginning if I click on notification tray item.

**Comment by lini** [comment]
Try closing the app fully and starting it again from the app icon on the device if it has been previously started using "tns run android". Using livesync or debugging might affect the way the app runs and manifest the undesired behavior you observed - refreshing the current page each time you bring the application to foreground.

If you can reproduce the issue consistently, please describe the steps you are making (e.g. using the demo app from this repository) so we can investigate further.

**Comment by prabudevarrajan1** [comment]
After adding the singleTop and running the app on the device, the app doesn't restart on notification tray item click.

Thanks all for investigating on this issue

**Comment by fthuin** [comment]
@lini This should be documented somewhere. Even if it's Android-specific, the default behaviour does not match the expected behaviour (restarting the app every time you click on a notification is quite weird IMHO).
