### ISSUE TITLE
Unable to read data in resume event

### ISSUE THREAD

**Issue by tomylee001001** [NativeScript/push-plugin#179]
when trying to get extras from the intent in the resume event i only get null object whichever key-value pair i send.i am using nativescript-angular with latest updates.
my code;
--------main.ts-------------------
import * as application from "application";
application.on(application.resumeEvent, function (args) {
    if (args.android) {
        var act = args.android;
        
        var intent = act.getIntent();
        var extras = intent.getExtras();
        console.log(extras);
        if (extras) {
            for (var key in extras) {
                console.log(key + ' -> ' + extras[key]);
            }
        }
    } 
});

notification code;
{
    "notification": {
        "title": "title",
        "text": "text"
    },
    "data": {
        "foo": "bar"
    },
    "priority": "High",
    "to": ""
}

**Comment by jogboms** [comment]
@tomylee001001 do you currently have any `launchMode` configuration in your manifest?

**Comment by tomylee001001** [comment]
yes i have this in my main activity android:launchMode="singleTop"

**Comment by jogboms** [comment]
Angular or NSCore?

**Comment by tomylee001001** [comment]
i am using Nativescript-angular.
i look at your code but i couldn't really understand it or how i will implement in my code.

**Comment by jogboms** [comment]
It involves using a custom Activity for android w/ RxJs

[Custom Activity](https://docs.nativescript.org/runtimes/android/advanced-topics/extend-application-activity#extending-activity)

**Comment by tomylee001001** [comment]
thanks.
After this implementation i will still going to get the data in resume event right?

**Comment by jogboms** [comment]
The gist shows you how to get the data after implementing the procedure.

**Comment by tomylee001001** [comment]
i tried your code and now i am getting this error when i try to build my app

app/android.activity.ts(10,25): error TS2304: Cannot find name 'AndroidActivityCallbacks'.
app/android.activity.ts(14,13): error TS2304: Cannot find name 'setActivityCallbacks'.

**Comment by jogboms** [comment]
@tomylee001001 did you import both of them?

**Comment by tomylee001001** [comment]
@jogboms  this time my build was ok but my app crashes without opening with a lot of errors. also it seems the file name for activity should be "activity.android.ts" instead of "android.activity.ts".
thanks for trying to help

**Comment by jogboms** [comment]
@tomylee001001 I just made some revisions to the gist. I initially forked it without making updates.

**Comment by tomylee001001** [comment]
My problem solved with the 1.0 verion of the plugin.
Thanks for helping
