### ISSUE TITLE
What AndroidManifest.xml should be checked? 

### ISSUE THREAD

**Issue by madsongr** [NativeScript/push-plugin#180]
In android Troubleshooting it says to check AndroidManifest.xml located at platforms/android/build/... but there are several manifest files in several folders. What's the right one?

**Comment by lini** [comment]
After you successfully build your project with the current NativeScript release 3.4.0, the manifest file with push permissions should be in:

    ./platforms/android/app/build/intermediates/manifests/full/F0/debug/AndroidManifest.xml

where FO and debug might be different (e.g. F1, release) depending on your configuration.

**Comment by madsongr** [comment]
I think if I can receive notifications using the code below so Manifest is ok, right?

`
curl -X POST --header "Authorization: key=****************************" --Header "Content-Type: application/json" https://fcm.googleapis.com/fcm/send -d "{\"notification\":{\"title\": \"My title\", \"text\": \"My text\", \"badge\": \"1\", \"sound\": \"default\"}, \"data\":{\"foo\":\"bar\"}, \"priority\": \"High\", \"to\": \"******************************************\"}"`

**Comment by lini** [comment]
Yes. if you can receive notifications from the Firebase console or by directly sending them with the above command line, then you Android app and manifest are configured correctly.

**Comment by madsongr** [comment]
Thanks for your attention!
