### ISSUE TITLE
Android notification not working on android 6.0.1

### ISSUE THREAD

**Issue by prabudevarrajan** [NativeScript/push-plugin#182]
I have two android device, one running the latest android 8.x and other running Android 6.0.1. Notification plugin works fine on the latest android, but not on android 6.0.1. 

Is there any specific push-plugin changes or configuration needed to make it work on older android version?

**Comment by DimitarTachev** [comment]
Hi @prabudevarrajan, there isn't any plugin-specific logic for Android 6.0.1.

One of our test phones is Nexus 5 with Android 6.0.1 and everything is working as expected.

Could you provide us with the following details:
 - Is it reproducible with the demo app of the plugin? (if not, provide us some code snippets)
 - Push plugin version
 - CLI version (run `tns --version` to fetch it)
 - Cross-platform modules version: (check the 'version' attribute in the node_modules/tns-core-modules/package.json file in your project)
 - Runtime version: (look for the "tns-android" property in the package.json file of your project)
 - Other plugins used in your app

**Comment by prabudevarrajan** [comment]
Hi, I was able to get notification working on android 6.0.x. Thanks a lot for investigating this issue.
