### ISSUE TITLE
How to retreive APNS and GCM token to use in own backend server 

### ISSUE THREAD

**Issue by smartsanja2013** [NativeScript/push-plugin#187]
I have own backend server which takes the device tokens from mobile and register them in aws sns for push notifications.
So i want to get APNS and GCM/FCM tokens from mobile app. How can i do it? All the examples I found is only for firebase. Is there a way to get them without firebase?

**Comment by madsongr** [comment]
If you take a look at demo folder you will find the functions to get the token when app starts.

For example:

‛‛‛
onRegisterButtonTap() {
        let self = this;
        pushPlugin.register(this.pushSettings, (token: String) => {
            self.updateMessage("Device registered. Access token: " + token);
            // token displayed in console for easier copying and debugging durng development
            console.log("Device registered. Access token: " + token);

            if (pushPlugin.onMessageReceived) {
                pushPlugin.onMessageReceived(this.pushSettings.notificationCallbackAndroid);
            }

            if (pushPlugin.registerUserNotificationSettings) {
                pushPlugin.registerUserNotificationSettings(() => {
                    self.updateMessage("Successfully registered for interactive push.");
                }, (err) => {
                    self.updateMessage("Error registering for interactive push: " + JSON.stringify(err));
                });
            }
        }, (errorMessage: String) => {
            self.updateMessage(JSON.stringify(errorMessage));
        });
    }
‛‛‛

**Comment by smartsanja2013** [comment]
Yes. In order to work this i need to hv setup the app in firebase. My question is can’t i get the token directly from apns/gcm without using firebase

**Comment by madsongr** [comment]
@smartsanja2013 Google has changed gcm to firebase a few years ago. I don't think it's possible to get a token without firebase because tokens are generated by fcm and push-plugin goes through fcm. I don't have much experience with iOS development so I don't know if there's another service for notifications. But if you intend to develop to android you will go through fcm anyway. FCM is Google. Android is Google. So...everything is connected.

**Comment by DimitarTachev** [comment]
@madsongr, thanks for helping with that!

@smartsanja2013, you cannot use the notifications without Firebase. You could find more details about the depreciation of GCM [here](https://developers.google.com/cloud-messaging/android/client).
