### ISSUE TITLE
Android push notification resumeEvent returns getExtras() event as "null"

### ISSUE THREAD

**Issue by prabudevarrajan** [NativeScript/push-plugin#193]
Following are the some of the Android scenarios on notification and I was able to get these following scenarios working
   

1.  App running on foreground - When notification arrives onMessageReceived() is successfully called. 

2.  App not running(Killed the app) - When notification comes it shows on the device notification tray, and I tap on the tray item, and it open the app, on "resumeEvent" got called and getExtras() was returning some data as expected.

The scenario that didn't work for me was 
 

3. App running in background - When notification comes it shows on the device notification tray and  I tap on the tray item, and it open the app, on "resumeEvent" got called and getExtras() was returning **"null"**

I am not sure why I am getting "null" on getExtras() call.

main.ts

```java
applicationOn(resumeEvent, function (args: ApplicationEventData) {
    if (args.android) {
        // For Android applications, args.android is an android activity class.
        console.log("Activity: " + args.android);
        if (args.android) {
            const act = args.android;
            const intent = act.getIntent();
            const extras = intent.getExtras();
            if (extras) {
                notificationUtil.setAutoShowNotification(true);
                console.log("If your notification has data (key: value) pairs, they will be listed here:");
                const keys = extras.keySet();
                const iterator = keys.iterator();
                while (iterator.hasNext()) {
                    const key = iterator.next();
                    console.log(key + ": " + extras.get(key).toString());
                }
            }
        }
    } 
});

```

package.json

```json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "com.x.x",
    "tns-ios": {
      "version": "3.4.0-rc-2017-12-4-1"
    },
    "tns-android": {
      "version": "3.4.0"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.1.0",
    "@angular/common": "~4.1.0",
    "@angular/compiler": "~4.1.0",
    "@angular/core": "~4.1.0",
    "@angular/forms": "~4.1.0",
    "@angular/http": "~4.1.0",
    "@angular/platform-browser": "~4.1.0",
    "@angular/router": "~4.1.0",
    "angular2-moment": "^1.7.0",
    "nativescript-angular": "^3.1.0",
    "nativescript-push-notifications": "^1.0.0",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "^3.3.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "babel-traverse": "6.25.0",
    "babel-types": "6.25.0",
    "babylon": "6.17.4",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.4.0",
    "typescript": "~2.4.2"
  }
}
```

**Comment by btulsi-ygrene** [comment]
I am facing same issue

**Comment by prabudevarrajan** [comment]
I was able to exactly reproduce this issue with the demo app on android. 

```
~/github/push-plugin/demo$ tns info
All NativeScript components versions information
┌──────────────────┬────────────────────────┬────────────────┬──────────────────┐
│ Component        │ Current version        │ Latest version │ Information      │
│ nativescript     │ 3.5.0-2017-12-20-10289 │ 3.4.1          │ Up to date       │
│ tns-core-modules │ 3.4.0                  │ 3.4.0          │ Up to date       │
│ tns-android      │ 3.4.0                  │ 3.4.1          │ Update available │
│ tns-ios          │ 3.4.0                  │ 3.4.1          │ Update available │
└──────────────────┴────────────────────────┴────────────────┴──────────────────┘
```

**Comment by tomylee001001** [comment]
i am having the same issue too.

**Comment by prabudevarrajan** [comment]
Also, make sure  android:launchMode="singleTask" is added to demo android app.

**Comment by jogboms** [comment]
@prabudevarrajan et @tomylee001001 see this [comment](https://github.com/NativeScript/push-plugin/issues/179#issuecomment-355738846)

**Comment by prabudevarrajan** [comment]
At the end of the https://github.com/NativeScript/push-plugin/issues/179#issuecomment-355738846 @tomylee001001  specifies that he use 1.0 and it worked for him.

I am using the latest push-plugin v1.0.0 and I am still facing the issue.

My package-lock.json file 

```json
{
"nativescript-push-notifications": {
      "version": "1.0.0",
      "resolved": "https://registry.npmjs.org/nativescript-push-notifications/-/nativescript-push-notifications-1.0.0.tgz",
      "integrity": "sha512-GLtFg1mxAg2oNsK+zg7g0fJUCgSizMuYIRIRswjL9/nI2MWLBmT5yV6z3udpBz8/IdyO5m/S6mpu57llq7g9gw==",
      "requires": {
        "nativescript-hook": "0.2.2"
      }
    }
}
```

In addition to the above version change can you please let me know what other changes that I need to do? 

Should i do all the changes that you mentioned in https://gist.github.com/jogboms/dec06ba426a42b14ebe1a0dba1611382 ?

**Comment by DimitarTachev** [comment]
Hi guys,

Changing the launchMode to `singleTop` or `singleTask` is changing the intent of an existing activity which wasn't handled by the NativeScript main activity.

We made an improvement which will fix the above-mentioned scenario by always providing the proper intent on application resume.

You could track the status of this pull request https://github.com/NativeScript/NativeScript/pull/5337 and update your nativescript-core-modules once the fix gets published.

Meanwhile, you could use [this workaround](https://github.com/NativeScript/push-plugin/issues/179#issuecomment-355738846) suggested by @jogboms or remove the custom launch event which will restart your app on notification click.

**Comment by DimitarTachev** [comment]
I'm closing the issue as the above-mentioned pull request was merged and the change is available in the next version of the NativeScript core modules.
