### ISSUE TITLE
Add support for GCM on iOS

### ISSUE THREAD

**Issue by manijak** [NativeScript/push-plugin#21]
The current state of the plugin does not allow us to use push notifications with GCM. There is no way to set the project/senderId in the iOS options. 

Please add support for GCM on iOS. Google has a well documented page on how to use their pod in iOS apps. 

https://developers.google.com/cloud-messaging/ios/client?ver=swift#set_up_your_cocoapods_dependencies

**Comment by raefa** [comment]
+1

**Comment by x4080** [comment]
+1

**Comment by spstratis** [comment]
+1

**Comment by spstratis** [comment]
Has anyone implemented a work around for this? Or could point me in the direction of understanding how to mimic the Native code that Google displays in their documents for getting GCM set up on iOS. Supporting both platforms on GCM is hugely important to me right now.

**Comment by alg** [comment]
@spstratis We are working on it with @raefa in our own project. We took this plugin as the basis and Android works just fine as it is. iOS on the other hand is whole different story. I managed to get tokens from GCM, but then... I can't receive a push. It says the push is sent, but I don't see it. On the second try the token is already invalidated for an unknown reason. I'm going through hell here figuring out what's going on. Will keep posted.

**Comment by manijak** [comment]
@alg & @raefa Awesome guys! If you need any help, just ask. I am no expert on iOS nor Android, but sometimes it helps to get a new pair of eyes on the issue :)

Are you using the pods that Google provides for the GCM? (the link I posted above).

**Comment by alg** [comment]
@manijak Cheers, mate. Yes, I linked in 'Google/CloudMessaging' pod.

**Comment by spstratis** [comment]
Thanks for the response! Look forward to hearing about what your approach is. Are you able to share any of your code? Completely understand if you can't.

**Comment by manijak** [comment]
I don't know if it helps, but found this article on how Xamarin implemented the integration to the GCM pod. It's not the same I know, but sometimes it helps you understand this better and to see if you've forgtten someting. 

I presume you have all certificates in order and uploaded to Google Dev center, and that you are only testing on real devices and not the simulator. 

https://components.xamarin.com/gettingstarted/googleiosgcm

**Comment by alg** [comment]
@manijak & @spstratis Sure, no problem. Here it goes: https://github.com/alg/push-plugin/tree/gcm

Here's how to call it (android & ios are the same):

    PushPlugin.register({
      senderID: "<your-sender-id>",
      sandbox:  true,
      badge:    true,
      sound:    true,
      alert:    true,
      notificationCallbackIOS: _onPushMessage
    }, function(token) {
      console.log("Got token: " + token);
    }, function(error) {
      console.log("Failed to register device with GCM: " + error);
    });

    if (Application.android) {
      PushPlugin.onMessageReceived(_onPushMessage);
    }

    function _onPushMessage(data) {
      console.log("Push Message:" + JSON.stringify(data));
    }

Once you get the token, you can CURL the packet to yourself:

    curl --header "Authorization: key=<your-key>" --header Content-Type:"application/json" https://android.googleapis.com/gcm/send -d "{\"to\":\"<your-token>\",\"notification\":{\"body\":\"Hello from GCM\"}}"

(Replace `<your-key>` and `<your-token>` above)

We'd appreciate if you let us know what's your milage with this. As I mentioned, the biggest problem at this point is getting the message received. You should see the message in log.

**Comment by alg** [comment]
@manijak Yup, I generated both dev and production APN certs, uploaded them to Google Dev and got the plist config. I'm testing on the real device and played with sandbox switch a bit to no effect. It doesn't matter if I start GGLContext and GCMService or not too. GCMService is said to be optional for APNs only functionality (no topics etc).

Thanks for the link. I'll study it now.

**Comment by alg** [comment]
Woohoo. It finally worked. It was something with the APN certs after all. When exporting from Keychain, don't expand the cert so that it shows the private key, just go for the cert itself and save it to .p12 without the password. When launching on device, set sandbox to TRUE. I still need to figure how to tell when it should be FALSE from inside the app, but for now it's TRUE. After this, the messages started coming.

**Comment by spstratis** [comment]
That's great news!  So you're now able to receive a notification from GCM on both platforms with out much custom code??

**Comment by alg** [comment]
@spstratis yes, just our modified push-plugin version and that same bit of JS do the job. I'm working on cleaning up the code for iOS so that it properly subscribes / unsubscribes from GCMService on app going active / background.

**Comment by manijak** [comment]
Great job guys! Time to test then :)

Regarding the sandbox flags, isn't that the flag that decides if you are in development or production mode? Why would you want to set it from inside the app?

**Comment by alg** [comment]
Updated the plugin. Two things to notice:

* You need to add `remote-notification` to `UIBackgroundModes` in `app/App_Resources/iOS/Info.plist` like below. Find `UIRequiredDeviceCapabilities` and add this section above or below:

        <key>UIBackgroundModes</key>
        <array>
            <string>remote-notification</string>
        </array>

* When testing, I had to make sure I have the correct Team set in XCode. Run `tns prepare ios`, the `open platforms/ios/hothealthapp.xcworkspace`, go to target's Genera tab and pick the right Team instead of None.

The first step can be done once. The second needs to be done every time you rebuild the app. If you know how to automate it, I'd be happy to know. Here's the guide on releasing where {N} guys mention this -- https://docs.nativescript.org/core-concepts/publishing-ios-apps.

**Comment by alg** [comment]
@manijak Well, it has to be set when you request the token from GCM. I have to decide whether it's sandbox or not. Simple as that. :)

**Comment by spstratis** [comment]
@alg as @manijak said great work! I will be testing it out this evening. As far as adding your fork of the plugin to my local project, will simply dragging and dropping it in and then making the necessary updates you mentioned  be all that is required or does {N} expect some other things to happen under the hood when you don't add a plugin using the standard tns plugin add <name> command?

**Comment by alg** [comment]
@spstratis thanks. We usually have node_modules.custom directory in the root of our project where we store custom versions of plugins and patched versions. You then just install them with `tns plugin add path-to-plugin`.

In this case, it needs a bit more work. Install the original plugin (nativescript-push-notifications), then copy it into `node_modules.custom`, then replace PushPlugin.framework file with this one (unzip it -- https://www.dropbox.com/s/n6itc3eletqzoip/PushPlugin.framework.zip?dl=0), then remove `/platforms/ios` and `/lib` and upon next building it will take the right plugin binary.

**Comment by spstratis** [comment]
@alg Cool thanks for the details. I'm still trying to wrap my head around the Nativescript workflow since I'm coming from a Native background.

**Comment by spstratis** [comment]
@manijak Have you had a chance to try this workaround yourself?

**Comment by x4080** [comment]
Great progress guys, little question, to generate iOS push certificate, we must be paid Apple developer or just Apple ID is sufficient?

Thanks and sorry for oot question

**Comment by raefa** [comment]
Sorry. You need an Apple Developer account.

__________________________
*Raef Akehurst*

raefakehurst@gmail.com
+61 (0)402 884 406

**Comment by x4080** [comment]
Thanks for the tip @raefa

**Comment by spstratis** [comment]
Hmm so I tried doing the same thing you guys  did to get push working for both iOS and Android using GCM but find when I get the registration token back on iOS and then try to send a message (using Postman) with that token in the request body to GCM I get an error saying "InvalidRegistration".

 I have uploaded the .p12 and to GCM and don't seem to have any issues getting a registration token back. I'm also using the correct auth key (I think) in the header of the post request. Did you guys run into this at all during your testing?

**Comment by alg** [comment]
This usually happens when your sandbox setting doesn’t match the environment. Before you release the app, it should always be Sandbox = true.

**Comment by spstratis** [comment]
@alg I have sandbox: true set in the PushPlugin.register() call, and the entitlement turned on in the capabilities sections of the project in Xcode. Is there another area where I need to set the sandbox = true?

**Comment by alg** [comment]
@spstratis not really, that should be enough. Also check that you have the dev cert uploaded to the correct spot in Google GCM portal. Other than this, it was a pretty easy setup for me.

**Comment by spstratis** [comment]
Damn, I guess I can try recreating the cert and re-adding it to GCM and see if that makes a difference

**Comment by manijak** [comment]
@alg, @spstratis 
Tested the plugin just now. Amazing work guys! Works great :) Both on Android and iOS. 

Two things that you need to look out for:
1) Make sure that the modified PushPlugins.framework is placed under platforms/ios of the plugin AND /project-folder/lib/  One of those did not get updated for me, so I did it manually. I noticed this when I saw that the format of the token was different compared to android. 

2) Initially I did not receive any notifications on iOS, even tho everything is set up correctly. I can even see the notification in the console when the app was running. Then found this: 
When sending notifications via POSTMAN or some other client, make sure do add this after the 'notification' data-segment: ```"priority": "high"``` Then they started poping up :)  Don't know the reason for this, but that was the only was I could get it working. 

```json
{
    "to": "lFNLYIAxn....",
    "notification" : {
        "title" : "MyApp",
        "body" : "GCM BABY!",
        "icon" : "icon",
        "color" : "#285681",
        "badge": 3, 
        "sound": "default" 
    },
    "priority": "high"
}
```

Also noticed that the notification only comes up when the app is closed or in the background. Not while you are navigating the app. 

Again, great work on this. This will be very useful. Thank you.

**Comment by manijak** [comment]
Btw, I do hope you guys make a fully working nativescript-plugin of this. Call it perhaps ```nativescript-gcm-plugin```

**Comment by alg** [comment]
@manijak You welcome, mate. Thanks for your details. I don't have issues with priority, but saw the mentions of this on Stackoverflow. You can update framework only in your custom plugin folder that npm is installing your plugin from (not node_modules, as it's being overwritten). Then before running `tns run ...` you just need to `rm -rf lib platforms node_modules`. Tns will reinstall all three and everything works. Thankfully, you don't need to do it every time unless you are making changes to the framework.

Re the plugin, you are right. I thought about this. Will probably do just that. Not going to support whole GCM thing though just yet, so it's probably nativescript-gcm-push or something along the lines.

**Comment by manijak** [comment]
I was just wondering, did you guys manage to get the badge/icon working on Android? It works fine on iOS but on android it just shows some colored shapes.

**Comment by alg** [comment]
@manijak We are using nativescript-local-notifications plugin for setting badges locally. I haven't checked remote version yet.

**Comment by gadonski** [comment]
i've been using this plugin in iOS but no response after register. Someone has any ideia?

**Comment by manijak** [comment]
@gadonski what do you mean by "no response"? You don't receive a token or no notification?
Are you using it on a real device? It will not work on simulator.

**Comment by gadonski** [comment]
@manijak sorry about the last message. So, i do not receive a notification. I've got a token but no notification has received on device (real device).

I've tried in android and ios on same time but only android has received.

**Comment by manijak** [comment]
Ok I see. Just check the console log, and compare the TokenIds you get from GCM. The GCM token is a very long string, while the one from APNS (apple) is shorter. If you get the shorter one on iOS, that means that you are not using the modified PushPlugins.framework linked earlier in this discussion by @alg 

If this is not the case, try sending the notification with ```"priority": "high"```

This was my issue the first time I ran the plugin.

**Comment by gadonski** [comment]
it's too strange. Sometimes the register works, but only receive push when the app is open. Sometimes the register do not work and return the error below:

```
NSConcreteNotification 0x156f459d0 {name = didFailToRegisterForRemoteNotificationsWithError; object = <Push: 0x156e512a0>; userInfo = {
    error = "The operation couldn\U2019t be completed. (com.google.iid error 7.)";
}}

```

How to receive push when the app is closed? And how can i fix this other error?

**Comment by alg** [comment]
@gadonski it's pretty tricky to diagnose why the APN messages don't go. There's APN debug mode that you can enable on device (see https://developer.apple.com/library/ios/technotes/tn2265/_index.html).

As for open vs closed... when the app is open, push notifications come through GCM service, not through the low-level APN / Android Push. When you go offline, Google uses the low level delivery mechanisms. That's why the two aren't related and you have to make sure both open and closed ways work before the release. I don't have any particular tips re debugging as we also struggle with making it work reliably across whole device range at the moment. On my side it all works in Sandbox mode, on the devices of other members of the team, only production mode works etc.

**Comment by manijak** [comment]
Hmmm. Weird. When I was testing, the notifications worked when the app was in the background and closed. But not while it was open and in use. Sandbox mode, iOS. 

I'll have to test again, also via TestFlight

**Comment by manijak** [comment]
Just to confirm, notifications work very well both via debug and production version. Again, good job guys! :+1:

**Comment by firecube** [comment]
Hi,

I have having the same issue as @spstratis and I get the error InvalidRegistration when trying to push to an iOS device.

The token I get from an iOS device registration is much smaller than the Android tokens and from what I can read, I think this means that this is a token from the Apple APN rather than GCM.

The Google docs seem to suggest that you need to call tokenWithAuthorizedEntity passing up the APN token and the GCM Sender ID to receive a GCM token but I can't see that anywhere in the code.  

Am I missing something?

I am using the code from here https://github.com/alg/push-plugin/tree/gcm.

Many thanks, Simon

**Comment by manijak** [comment]
@firecube The reason you are getting the APNS token and not the GCM token, is because you didn't add the modified `PushPlugin.framework` from @alg. You can download it here, replace the one in the `node_modules\nativescript-push-notifications\platforms\ios\`  . I had to also replace the one in the \lib\ folder.

https://www.dropbox.com/s/n6itc3eletqzoip/PushPlugin.framework.zip?dl=0

**Comment by firecube** [comment]
@manijak Thanks!  I had already used that version but I hadn't updated the one in the lib directory.

**Comment by manijak** [comment]
I did notice one issue with this after I started testing with Android. And that is that the callback function for when receiving the notification, does not contain the notification payload on Android. It is always empty. While on iOS you get the entire object that you can parse. 

Any way we can include the data-payload in android as well?

**Comment by alg** [comment]
@manijak yes, I found that we have to send notification part (title, body, tag, icon, color, sound etc) in both `notification` field and `data` fields to get them on both iOS and Android. So basically, in Ruby it looks like this:

    notification = {
      title:  "title",
      body:   "message",
      tag:    "events",

      icon:   ANDROID_ICON,
      color:  ANDROID_ICON_COLOR,

      # Android handles this extension even though it's mp3 really
      sound:  "notification.caf"
    }
    
    data = {
      payload_field_1: "...",
      payload_field_2: "..."
    }
    
    # Android push plugin lib doesn't pass notification to us, so we have to include it into data payload
    data.merge!(notification)

    # Add badges info
    badge_total, badge_details = BadgeInfo.calculate(...)
    notification[:badge] = badge_total
    data[:badges] = badge_details

    # Deliver notification
    res = Pusher.deliver(tokens, {
      notification: notification,
      collapse_key: notification[:tag],
      data:         data
    })

`Pusher` is our own wrapper to `GCM` gem that handles the response, but otherwise just sends the keys (notification, collapse_key, data) as-is. You will find them in GCM docs.

On the JS side we handle it like this:

    exports.init = function() {
      PushPlugin.register({
        // ...
        notificationCallbackIOS: _oniOSPushMessage
      }, function(token) {
        console.log("Got token: " + token);
        // ...
      }, function(error) {
        console.log("Failed to register device with GCM: " + error);
      });

      if (Application.android) {
        PushPlugin.onMessageReceived(_onAndroidPushMessage);
      }
    };

    function _oniOSPushMessage(data) {
      _onPushMessage(data);
    }
    function _onAndroidPushMessage(_message, json) {
      _onPushMessage(JSON.parse(json));
    }
    function _onPushMessage(data) {
      if (!data.tag) return;
      console.log("Push message data: " + JSON.stringify(data));

      Badge.fromPushNotification(data);

      LocalNotifications.schedule([{
        id:     data.tag,
        title:  data.title,
        body:   data.body,
        sound:  data.sound,
        badge:  data.badge
      }]);
    }

**Comment by manijak** [comment]
Thanks @alg, this helped. I was missing this part:
```js
function _onAndroidPushMessage(_message, json) {
  _onPushMessage(JSON.parse(json));
}
```
I had only one parameter here, and the first one is always empty for some reason. When I added the second one, it worked. 

Too bad that the hybrid-payloads for iOS and Android are different. iOS receives both, no need to merge them. Android should work the same way, GCM documentation tells the same.  

Few other things missing in Android compared to iOS:
- No "foreground" flag included, tells us if the notification was received while the app was closed or in use.
- And the `onMessageReceived`is not fired unless the app is active. So if you tap on a notification outside the app, the above event never fires. So you can't parse the data-payload. 

Odd that the iOS version works better than Android one 😄

**Comment by manijak** [comment]
A message from Google:
"Firebase Cloud Messaging (FCM) is the new version of GCM. It inherits the reliable and scalable GCM infrastructure, plus new features! See the FAQ to learn more. If you are integrating messaging in a new app, start with FCM. GCM users are strongly recommended to upgrade to FCM, in order to benefit from new FCM features today and in the future."

https://developers.google.com/cloud-messaging/

**Comment by alg** [comment]
@manijak as if we didn't have better things to do 😄 Thanks, mate. I'll have a close look later today.

**Comment by alg** [comment]
@manijak I don't believe everyone will eagerly migrate. From what I understand, Firebase isn't free, and so their FCM is also cost money.

**Comment by manijak** [comment]
@alg FCM is the new GCM. So users will not have a choice. It's a must, eventually. 

And as I understand it from their FAQ, it will still be free:

Cloud Messaging: Do I need to use other Firebase services in order to use FCM?
You can use Firebase Cloud Messaging as a standalone component, in the same manner as you did with GCM, without using other Firebase services.

**Comment by tieoneease** [comment]
Hi, I am having issues getting a token using your PushPlugin.register. It's not logging any message at all (no errors either). Any thoughts?

**Comment by alg** [comment]
@tieoneease You might want to check if you have Push Notifications setup on the platform you are trying to run. GCM builds on top of the native features. Check out this thread for hints on what might be wrong. I think we have already covered all of it here.

**Comment by lowe0292** [comment]
@alg any word on FCM support? We're just starting a new app, and Google recommends using FCM over GCM for new projects.

**Comment by alg** [comment]
@lowe0292 sorry, mate. I was busy with something else whole last month. Let me see if I can have a close look by the end of the week.

**Comment by vcorr** [comment]
@alg When you do start to support FCM, also consider adding topic support while your at it.
(There's another ticket for it here: https://github.com/NativeScript/push-plugin/issues/28)

**Comment by alg** [comment]
@vcorr I'm not the owner of this project. :) I have a fork where this GCM support is implemented. We hang out here as it all started with this thread. You guys are welcome to work on some stuff too. :D

**Comment by manijak** [comment]
Yeah you are right, I don't think nativescript-team is going to do anything with this. 
The propper discussion place around the modified version of the push-plugin is here: https://github.com/alg/push-plugin/tree/gcm

**Comment by vcorr** [comment]
@manijak Ok... now I'm a little confused. Isn't this push-plugin also based on gcm? At least the android native source uses it. So why is there a separate fork for gcm? Just interested to hear the history of this :)

**Comment by alg** [comment]
@vcorr Initially GCM (Google Cloud Messaging) was implemented for Android only and that's why this push-plugin supports it for Android. Then Google added support for iOS devices and Web. In order to benefit from its simplified and unified model I forked and updated this plugin. Now both iOS and Android platforms work on top of GCM (in my fork). As far as I know, this plugin was never updated.

**Comment by manijak** [comment]
@vcorr : Yes this is the official NativeScript push-notifications-plugin and supports GCM but only on the Android side. The iOS side uses either Telerik services or Apples APNS for notifications. 

The modified version that I linked to above, is the one that the community created (mostly @alg) so that the iOS side also supports GCM.

**Comment by vcorr** [comment]
@manijak @alg Thanks, now I understand :)

**Comment by spstratis** [comment]
@alg based off of a conversation I was having with manijak, I'm curious as to how you are handling Push token refreshes. Are you refreshing tokens after a certain amount of time or do you reregister every time the application is restarted?

**Comment by alg** [comment]
@spstratis I didn't touch Android part and it looks like there's the callback for when there's a refreshed token -- onTokenRefresh. The iOS version doesn't expose anything like it, but it goes through the whole cycle instead and calls the same got-token callback that you pass to the PushPlugin.register(...) call.

It's a good practice to re-register every time you start the app. The tokens will update if necessary, or will remain the same if nothing change. You will also know if the user still wants notifications. Of course, for the long-running apps it may be important to refresh tokens, but I'm yet to see it in practice.

**Comment by spstratis** [comment]
@alg Thanks for the feedback, that's inline with Manijak's approach. I was already reregistering on every restart by default, the 'onTokenRefresh' event made me feel like there was something I was missing doing it that way though.

**Comment by alg** [comment]
Just started a new plugin project (https://github.com/alg/nativescript-fcm). After looking through the FCM docs, it doesn't make sense to drag this legacy API. FCM is *much* simpler than GCM API-wise. I'll be working on Android version first.

**Comment by spstratis** [comment]
I'm sure us here won't mind helping with that where ever we can.

**Comment by DimitarTachev** [comment]
Hi guys, I'm closing this one as GCM (Google Cloud Messaging) is deprecated by Google.

This plugin is using directly the APNs (Apple Push Notifications service) on iOS. If you wanna use FCM (Firebase Cloud Messaging, the GCM replacement) on both Android and iOS, I suggest you use Eddy's firebase plugin. Take a look at [this readme](https://github.com/EddyVerbruggen/nativescript-plugin-firebase/blob/master/docs/MESSAGING.md) for more details.
