### ISSUE TITLE
google-services.json search doesn't respect nsconfig.json

### ISSUE THREAD

**Issue by ceph3us** [NativeScript/push-plugin#219]
The nsconfig.json isn't checked for the appropriate resources path, so if a project uses nsconfig.json to define a custom path for the app, it won't work correctly unless the standard app/App_Resources hierarchy is created.

### Which platform(s) does your issue occur on?
- Android (only platform needing google-services.json)

### Please, provide the following version numbers that your issue occurs with:

- CLI: 4.0.0
- Cross-platform modules: 4.0.0
- Runtime(s): Android - 4.0.1
- Plugin(s): nativescript-angular, nativescript-push-notifications

### Please, tell us how to recreate the issue in as much detail as possible. 
Set up a new NativeScript project for Android, put an nsconfig.json in the base with the key `appResourcesPath` set to a non-default location, and then put a valid `google-services.json` there under the Android subfolder.

### Is there any code involved? 
Should show on any project with the setup as above.

**Comment by zbranzov** [comment]
The fix is released in 1.1.4 version of the plugin.
