### ISSUE TITLE
Question about how to create this plugin

### ISSUE THREAD

**Issue by x4080** [NativeScript/push-plugin#22]
Hello, this plugin is not cocoapod plugin?
1. How to create the PushPlugin.framework used in nativescript ? I mean the relation between the PushPlugin IOS xcode source and the PushPlugin.framework folder used in nativescript ?
2. Is it better to create plugin in this fashion or use cocoapod? Maybe this is better since it directly talk to nativescript ?

Thanks

**Comment by AntonDobrev** [comment]
@x4080 

This is not a CocoaPod package. A plugin that is using a CocoaPod is this one [NativeScript dialog](https://github.com/enchev/nativescript-dialog). 

1. The PushPlugin.framework is a native library that packs all needed native code. You can examine the xcode project in native-src/ios. The built framework is available at platforms/ios. The way they are exposed to the project can be examined in push-plugin.ios.js. 

2. Both ways of packaging your own custom native code (either via a framework or a CocoaPod) should be usable in NativeScript. More on using CocoaPods in your NativeScript app is available [here](http://docs.nativescript.org/plugins/cocoapods).

**Comment by x4080** [comment]
thanks for the answer
