### ISSUE TITLE
Why I didn't receive push notification when app is closed?

### ISSUE THREAD

**Issue by madebyais** [NativeScript/push-plugin#23]
I didn't receive any push notification when the application is closed. 

Did I missed any configuration?

Please kindly advice. Thank you!

**Comment by vbresults** [comment]
Does your APNS message have the content-available flag set?

**Comment by AntonDobrev** [comment]
@madebyais 

Is this for Android or for iOS?

For Android a similar issue is discussed in #1, can you please take a look?

For iOS - do you have allowed the alert/banner and the notifications at all for the app?

**Comment by madebyais** [comment]
@vbresults @AntonDobrev 

This is for android. Thank you @AntonDobrev , I'll take a look on it.
