### ISSUE TITLE
When app is closed onMessageReceived function is not executing

### ISSUE THREAD

**Issue by karteek42** [NativeScript/push-plugin#26]
Hi,

I'm using this push-plugin in my app(Android, NativeScript) for receiving push notifications.When ever one push notification came, I need to save the contents of that notification into database.
For that I have written code in onMessageReceived function.If app is running then onMessageReceived function is executing.But if app is not running then notification is coming, onMessageReceived function is not executing.Any suggestions??

**Comment by AntonDobrev** [comment]
@karteek42 

Indeed, the behavior is intended in the Android implementation - when the app is not running the plugin will construct a notification and place it in the notification tray. Subsequently when the user taps on this entry the app will be opened and the JavaScript _onMessageReceived_ callback will be executed. 

You can refer to the relevant code in the Android implementation [here](https://github.com/NativeScript/push-plugin/blob/master/native-src/android/src/com/telerik/pushplugin/PushPlugin.java#L112).

**Comment by skrichten** [comment]
I have a use case where we need onMessageReceived to execute as soon as the message is received. Any chance of making that an option?  I'm trying to choose between NativeScript and Xamarin right now.  It looks like there is a Xamarin plugin that does allow this...

https://github.com/rdelrosario/xamarin-plugins/tree/master/PushNotification

"On the Android Application class, is better to use the OnCreate of the Android Application class so you can handle push notifications even when activities are closed or app not running by using our PushNotificationService to keep listening to push notifications."

**Comment by AntonDobrev** [comment]
@skrichten - the implementation suggestion you referred to is similar in the plugin as well as you can see [here](https://github.com/NativeScript/push-plugin/blob/master/native-src/android/src/com/telerik/pushplugin/PushHandlerActivity.java#L19). 

However, the notification is processed on the native level and the app is awaken - however, this places a notification in the bar. Tapping on the notification will call the onMessageReceived callback.

Is this answering your question, can you explain your use case in more detail?

**Comment by spstratis** [comment]
@AntonDobrev I have an additional question on this. If I need to alter the notification string that displays in the notification tray so that numbers displayed within the notification can be localized to the language of the device. Would I need to send the notification as a Data message instead of a Notification?

**Comment by DimitarTachev** [comment]
Hi guys,

GCM (Google Cloud Messaging) was deprecated by Google and the plugin is now rewritten using the Firebase Cloud Messaging (FCM). The FCM messages handling is explained in [this readme section](https://github.com/NativeScript/push-plugin#receive-and-handle-messages-from-fcm-on-android).

Regarding the localized messages, this could be achieved with mixed notifications containing localized keys and some business logic in your app.
