### ISSUE TITLE
pushPlugin.register() not working in app.js on iOS

### ISSUE THREAD

**Issue by einicher** [NativeScript/push-plugin#27]
Hi,

pushPlugin.register() is working normally inside page javascripts, but for the notifications i need it to run in app.js where it is simply doing nothing if i put it there.

Is this an error or expected behavior?
How do you manage anytime background notifications if not in app.js?

**Comment by AntonDobrev** [comment]
Hi @einicher 

In app.js you may use the `register` logic as follows:

```
application.on(application.launchEvent, function (args) {
	var pushSettings = {
		...
	};

	pushPlugin.register(pushSettings, function () {
		console.log("Registered");
	}, function (err) {
		console.log("Cannot register");
	});
});
```
This way you will ensure that the correct callbacks and settings are called when the app is launched. When the app is not running, the plugin (for Android) and the OS (for iOS) will take care to display a banner/alert when a notification is received. 

Let me know if this answers your question.

**Comment by einicher** [comment]
Hi, thank you!
When i do that i get “Fail to load module /data/data/<appID>/files/app/app.js”
Added/removed node_modules and platforms and rebuilt it several times - same outcome.

**Comment by einicher** [comment]
its easy: `var pushPlugin = require('nativescript-push-notifications');` has to be inside the launchCallback:
```
application.on(application.launchEvent, function (args) {
    var pushPlugin = require('nativescript-push-notifications');
    var pushSettings = {
        ...
    };

    pushPlugin.register(pushSettings, function () {
        console.log("Registered");
    }, function (err) {
        console.log("Cannot register");
    });
});
```
