### ISSUE TITLE
Conflict w/ nativescript-google-maps-sdk plugin

### ISSUE THREAD

**Issue by dklinzing** [NativeScript/push-plugin#29]
There seems to be a conflict between the nativescript-google-maps-sdk plugin and the push-plugin.  The push plugin is referencing the google play services 8.4.0 but the nativescript google maps sdk plugin is referencing the newest google play services version installed.  

I talked w/ the nativescript-google-maps-sdk plugin developer @dapriett and he thought it might be best to add the following line to your plugin's gradle file so it always targets the latest installed version?
	compile 'com.google.android.gms:play-services-maps:+'

Thoughts?  Here's the open issue I have on his plugin:
https://github.com/dapriett/nativescript-google-maps-sdk/issues/34#issuecomment-222698981

**Comment by AntonDobrev** [comment]
@dklinzing Thanks, you are correct, for better compatibility the plugins should be referencing the latest version of the SDK available on the server. 

I have proposed this to the collaborators of the plugin as an enhancement. Meanwhile you may manually modify the plugin config.

**Comment by dklinzing** [comment]
Do you have any sense of an ETA when/whether this change can/will be made?  We use the Telerik Platform and are referencing your npm package currently, so we'd have to figure out a work-around.

**Comment by AntonDobrev** [comment]
@dklinzing 

Daniel, my apologies for the delayed reply. 

Given that the latest Google Play Services SDK (9.0.0) requires the explicit _applicationId_ in the gradle file, the collaborators of the plugin postponed this for a future version when there is officially added support for this in NativeScript. Please see https://github.com/NativeScript/android-runtime/issues/454 

Otherwise adding manually the _applicationId_ will cause similar issues to all users, not only when conflicting with other plugins. 

Meanwhile the plugin package can be referenced from a forked repository of the plugin where the dependency is changed to build against the latest (or compatible) Google Play Services SDK. After this point your app to the edited module using the instructions from [here](http://docs.telerik.com/platform/appbuilder/nativescript/working-with-custom-modules/manage-custom-modules-package-json).

**Comment by krismcfarlin** [comment]
I am having the same problem with the push notifications plugin.  I believe it has to do with GPS sdk but have tried + for version number fix which didn't work.  It might also be a gradle issue and the format of the gradle as android studio is complaining when I open the project and want to automagically update the gradle format.

**Comment by AntonDobrev** [comment]
Fixed in 0.0.17.

**Comment by swinn77** [comment]
my AVD stopped showing google MAP
![untitled](https://cloud.githubusercontent.com/assets/15188441/23295816/4fe83f6c-fa98-11e6-81a9-8a23b2e9510e.png)

pl help

**Comment by AntonDobrev** [comment]
@swinn77 This error sounds that you have updated a framework (probably the Google Play Services SDK) in your app but the device does not contain this version. That is why the error message is advising to update the Google Play services on the device. To do so in the emulator - you should update the image to include a higher Google Play services version support.

**Comment by swinn77** [comment]
@AntonDobrev Thanks, ur reply is much appreciated, can u pl advice if i can downgrade the framework or how can i get update image to match the requirement to mitigate the issue. Pl elaborate

**Comment by randy-johnson** [comment]
This also happened tonight on a colleagues android device.  He needed to sign into his account on the device so the device would install updates from the play store.  One of those updates was the play store service.  Once we has up to date on his updates the page worked fine.  

Same happened on my genymotion emulator.

I followed these steps and boom I got my map back:


	* Visit opengapps.org
	* Select x86 as platform
	* Choose the Android version corresponding to your virtual device
	* Select nano as variant
	* Download the zip file
	* Drag & Drop the zip installer in new Genymotion virtual device (2.7.2 and above only)
	* Follow the pop-up instructions

**Comment by mshanak** [comment]
you need to change the versions;
this is what finally worked for me:

in (app/App_Resources/android/app.gradle ) add the following code at the top
```
project.ext {
    googlePlayServicesVersion = "10.0.0"
}
```

then in (platforms/android/build.gradle)
 replace this line
`classpath "com.google.gms:google-services:+"
`
with this line:
`classpath "com.google.gms:google-services:3.0.0"
`
