### ISSUE TITLE
Notifications aren't displayed

### ISSUE THREAD

**Issue by Edujugon** [NativeScript/push-plugin#34]
When the device sets the app under doze mode, any notification sent to that app is not displayed. Even sending the notification with high priority as GCM recommend.

Any idea around this issue?

**Comment by AntonDobrev** [comment]
@edujugon I assume you refer to an app called Doze available in Google Play. In this case the issue may be that the app is prevented to run in the background and this way - it cannot process the received event and display the notification in the tray. Could you please check this on your side?

**Comment by edujugon** [comment]
@AntonDobrev We've created some apps with nativescript which support push notifications thanks to your package.

The thing is in android, when the apps aren't used by the user for some time, the system sets the apps under doze mode (a feature of android to save battery).

So always, when the apps are under that asleep mode, they don't display the notifications. But the GCM response exposes the notifications as sent and received.

Everything works fine if the apps don't fall into that mode..

Just was wondering if you had faced that behaviour..

**Comment by AntonDobrev** [comment]
@edujugon Eduardo, can you please refer to this [article](http://docs.telerik.com/platform/knowledge-base/troubleshooting/troubleshooting-cannot-receive-push-notifications-on-android-when-the-app-is-closed) to check for particular behavior on some devices and if it fixes the issue.

**Comment by edujugon** [comment]
@AntonDobrev 

I've checked the provided article but it's not my case. I've tested it in several devices of different manufacturers. personally I could tested it in a Samsung galaxy Note 4...

The thing is when the device enters Doze mode, the app doens't display any notification. Please refer to this [article](https://developer.android.com/training/monitoring-device-state/doze-standby.html) about Doze mode on Android system.

As suggested by google, when you really need a important notification is  displayed, you have to set the priority parameter to high, where in theory it should awake the app and display the notification.

I set up everything as suggested but the notification is not displayed... And it's displayed only when the app is no in Doze mode..

**Comment by AntonDobrev** [comment]
@edujugon Thanks, this is very useful information. 

My understanding is that there are a few things to think of:

* Build the plugin with the latest Google Play Services SDK (at the moment it is hard-coded to 8.4.0). This can be easily done with modifying the  `platforms/android/include.gradle` file to point to `compile 'com.google.android.gms:play-services-gcm:+' `. Make sure that you have installed the latest SDK on your build machine. This should ensure that the GCM connection is successfully able to understand the 'high' priority in 'Doze' mode. 
* Connect your device to the Android Device Monitor, enter Doze mode and send a push notification. Examine for any relevant debug information. 
* Ensure you are sending the relevant payload to GCM required to set the priority to 'high' and if it is respected by the service used to communicate with GCM. 

Could you please check the above on your side and let me know the results?

**Comment by Edujugon** [comment]
Yeah!

I'll have a look at that and get back to you with some updates.

**Comment by Edujugon** [comment]
@AntonDobrev

Sorry for my delay in reply, I'm out of my country for some days...

After checking the above points and test it in a real device I can say that now, it works as expected :)

Anyway, I'll test it on more devices and if there was any issue regarding this matter I would get back to you with the news.

**Comment by AntonDobrev** [comment]
@Edujugon Thanks for specifying this, please confirm what exactly fixed the issue after you test, I suppose this was the latest SDK along with setting the correct priority in the payload, should work as expected.

**Comment by Edujugon** [comment]
@AntonDobrev 
Sorry for my delay in reply. I've just got home...

Yeah! that was. Updating the SDK to the last version made it work :)

**Comment by AntonDobrev** [comment]
@Edujugon Glad that this is working. Will be closing this question and perhaps the gradle dependency will be added on plugin level in future releases to ease this procedure.
