### ISSUE TITLE
Broken if app id changed

### ISSUE THREAD

**Issue by baderth** [NativeScript/push-plugin#35]
leaving id at default, eg "org.nativescript.someApp" everything is fine.
Changing to "com.xxxxx" (for submitting an update to playstore, makes no difference if just changed in the package.json or anywhere found) and the build goes fine but app crashes with:

"TypeError: Cannot read property 'pushplugin' of undefined File: "<unknown>, line: 1, column: 265"
when the pushplugin is invoked.

Maybe i'm just missing something here or its not even pushplugin related but invested several hours now and i'm lost.

TIA

![image](https://cloud.githubusercontent.com/assets/1823917/17618185/85aff95a-607e-11e6-8777-1127e58cdefe.png)

**Comment by AntonDobrev** [comment]
@baderth 

This looks like the id is set in the package.json file. Some NS app projects also have an app.gradle file for Android in /App_Resources which should be the same as in the package.json file. 

Could you please check this?

**Comment by baderth** [comment]
@AntonDobrev 

thanks.

yeah, as I stated in OP -  i searched through the whole folder after doing a fresh "platform add android" and changed every occurrence of the "default" app id to mine, but gave me the error from the OP.

**Comment by baderth** [comment]
@AntonDobrev 

Issue is resolved with latest 2.2 NS.

**Comment by AntonDobrev** [comment]
@baderth Thanks for specifying, closing this issue now. Happy coding!
