### ISSUE TITLE
Display badge number on android

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/push-plugin#36]
Hello,

I have everything working well on iOS, but I was wondering if there is a way to display application icon badge on Android as well?  Currently, when the push notification is sent, the application icon does not show a badge.

Thank you.

**Comment by dpdragnev** [comment]
I just read a post that stated that Android does not support badges on application icons.  Closing this question

**Comment by Daxito** [comment]
I have Android phone, and I have whatsapp, and whatsapp can do this, how come?? interesting...

**Comment by dpdragnev** [comment]
This is a very good point.  Facebook does it as well.  I wonder how they do it.

**Comment by AntonDobrev** [comment]
@Daxito @dpdragnev 

Some Android distributions with custom launchers (this is a prerequisite) allow for application icons which can be set programmatically. This however, does not work on the stock Android. The [Android notification guidelines](https://material.google.com/patterns/notifications.html) do not mention anywhere badging of the app icon.
