### ISSUE TITLE
Permission request dialog shown behind app in iOS

### ISSUE THREAD

**Issue by dpdragnev** [NativeScript/push-plugin#38]
Hello,  

Do you know what could be causing the permissions request dialog on iOS to show behind the app?  It actually flashes quickly and then goes behind.  I have to press the home button to bring it to the front.  Until then the UI is blocked. 

I am using Everlive and I am calling the register method in the app's launchEvent as such:

`var pushSettings = {
        //iOS - specific settings
        iOS: {
            badge: true,
            sound: true,
            alert: true,
            clearBadge: true
        },
        notificationCallbackIOS: function (userInfo) {
            ...
        },
        //Android - specific settings
        android: {
            projectNumber: '944301213976'
        },
        notificationCallbackAndroid: function callback(data) {
            ...
        }
    }

    el.push.register(pushSettings, function (data) {
        ...
    }, function (error) {

    });`

Thank you.

**Comment by AntonDobrev** [comment]
@dpdragnev Thanks for reporting this, this is indeed peculiar. The permissions alert is handled on iOS-level when the native push registration functionality is invoked. This said, I wasn't able to reproduce the issue on iOS 9.3.4 device and NS 2.0.0 and 2.2.0. 

Also, I used an approach with registering for push in the application launch event and with a button that calls the register method. 

My suggestion would be to again remove and add the iOS platform, then rebuild the app and redeploy it. 

The warning that the remotenotificationstypes are not supported in iOS 8 is a minor one and should not affect the behavior in question. 

Could you please try this on your side and share the results? Please mention this issue in your SOF thread or redirect it to here as well.

**Comment by dpdragnev** [comment]
Thank you @AntonDobrev 

I am using the AppBuilder so I am not adding the platform explicitly, but will try putting the code in a button tap event to see if this will make a difference.  I will post my finding here shortly.

**Comment by dpdragnev** [comment]
@AntonDobrev,

Originally I was running the code during the app load and it seems that after the popup appeared, the first screen to load took the focus hiding the popup.  Once I placed the code in a button tap handler, it started working fine.

I am not sure if this is the intended behavior, but it is working from the tap event, so at least we have a workaround.

Thank you for the suggestion.
