### ISSUE TITLE
Sending notification icon URL (GCM)?

### ISSUE THREAD

**Issue by jaysson** [NativeScript/push-plugin#39]
I see in Notification.Builder code that I can pass a drawable name from server. However, I don't see how I can pass an image URL.

Is there a way to do it? If not, is there any plan to do it?

**Comment by AntonDobrev** [comment]
@jaysson Yes, you can use the following keys in the server payload:

_largeIcon_
_smallIcon_

to specify the assets to be used when displaying the notification in the tray or when expanding it. 

The plugin is following the specifications outlined in the Telerik Platform Notifications service for setting the icons for Android as explained [here](http://docs.telerik.com/platform/backend-services/javascript/push-notifications/send-and-target/push-send-target-examples#setting-custom-notification-icons-on-android).

**Comment by jaysson** [comment]
No, that's not what I was asking.

largeIcon and smallIcon have to be drawables - that is, I have to bundle the icons in the app. My question is how can I pass a URL.

I am building a social app, and I need to show notifications with images of users (like any messaging app). These images are on server.

Something similar to what phonegap has.
https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/PAYLOAD.md#images 

Remote URL section:
```
{
    "registration_ids": ["my device id"],
    "data": {
        "title": "Large Icon",
        "message": "Loaded from URL",
        "image": "https://dl.dropboxusercontent.com/u/887989/antshot.png"
    }
}
```

**Comment by AntonDobrev** [comment]
@jaysson 

I understand your use case. The remote URI for an image/icon is not yet implemented in the plugin and that is why I added an enhancement tag. 

Meanwhile, you can easily adjust this on your side with modifying the [notification builder logic](https://github.com/NativeScript/push-plugin/blob/master/native-src/android/src/com/telerik/pushplugin/NotificationBuilder.java#L72) to read a key in the remote notification payload and parse its URI as a Bitmap resource and set it to the notification as a small/large icon.

**Comment by DimitarTachev** [comment]
GCM (Google Cloud Messaging) is deprecated by Google and the plugin is using the Firebase Cloud Messaging (FCM).

Regarding the icon URL in FCM, the default one [could be set in the manifest file](https://github.com/NativeScript/push-plugin#setting-notification-icon-and-color) and [overridden in the firebase notification payload](https://firebase.google.com/docs/reference/admin/node/admin.messaging.NotificationMessagePayload#icon) for each notification.
