### ISSUE TITLE
Get application state(Foreground/Background) when notification is received

### ISSUE THREAD

**Issue by hvadotnarola** [NativeScript/push-plugin#42]
Hello,

Is there any event or flag that we can get application state when the notification arrives. I have a case when notification arrives, user clicks on notification and application is in background/killed. So on Click of notification application should navigate to page specified. This way works fine when app is in Killed state. But when application is in foreground and user is viewing app, and notification arrives. Then due to navigation code application navigates to that view automatically. I mean that should not happen if user is using application. I am handling navigation on `onMessageReceived` method.

So i am seeking for either we can get event for notification tap OR at least return application state when notification arrives.

Thanks in advance

**Comment by AntonDobrev** [comment]
@hvadotnarola You will receive a _foreground_ boolean property in the event arguments of the notification received callback which can be used to determine the app state.

**Comment by hvadotnarola** [comment]
Sorry I tried to implement but when on receiving notification its not returning application state.
Would you please provide snippet where on receiving notification, it also returns application state and the payload ? @AntonDobrev

**Comment by ralphpig** [comment]
@hvadotnarola Did you ever figure that out?

**Comment by hvadotnarola** [comment]
I guess there is no flag passes (i tried) and i had switch to firebase-plugin.

**Comment by AntonDobrev** [comment]
Example:

For Android:
```
function onAndroidPushReceivedCallback(message, data, not) {
    if (data.foreground) {
        // app is in the foreground
    }
}
```
More details on the way of handling Android notifications [here](https://github.com/NativeScript/push-plugin#receive-and-handle-messages-from-fcm-on-android). 

For iOS:

```
function onIosPushReceivedCallback(args) {
    if (args.foreground) {
        // app is in the foreground
    }
}
```

**Comment by kunaldodiya** [comment]
is there any way that i can subscribe to event change ??? i want to update current status of every user device to show whether user is online or offline, is there any event trigger before user close app / force close app / minimize  app or just shift focus from current app to another app ???? so i can set this device is currently inactive and othere people can see offline / away message ????

**Comment by lini** [comment]
You can use the application events to know when an app is lauched, suspended, etc. Link to the documentation: https://docs.nativescript.org/core-concepts/application-lifecycle#use-application-events
