### ISSUE TITLE
The plugin breaks on IOS10

### ISSUE THREAD

**Issue by ignaciolarranaga** [NativeScript/push-plugin#43]
Check out the pull request here with the solution: https://github.com/NativeScript/push-plugin/pull/41

Best

**Comment by timricker** [comment]
+1 Can this pull request please be released?

**Comment by moreaup** [comment]
Do you have some news ?

**Comment by ignaciolarranaga** [comment]
No yet guys, but you can use my fork in the meantime if useful: https://github.com/ignaciolarranaga/push-plugin

**Comment by moreaup** [comment]
Hey,

Any update on the release fix ?

**Comment by AntonDobrev** [comment]
@ignaciolarranaga Thanks for your contribution. May I please ask, are you building with iOS 10 SDK and Xcode 8? I need to consult this with NativeScript iOS runtime but it appears that the issue appears in the above environment and the fix will not work if the app is built against a lower iOS SDK.

**Comment by ignaciolarranaga** [comment]
Hi @AntonDobrev, yes I'm with iOS 10 / Xcode 8, and you are correct for lower SDKs it will not work, probably a test to detect which structure has to be used ?

**Comment by AntonDobrev** [comment]
@ignaciolarranaga Thanks for specifying this. 

I commented with the most robust solution (at least on first sight) in the PR. I believe that we should strive to add a more robust solution in the plugin.

**Comment by thomasmoon** [comment]
@AntonDobrev @ignaciolarranaga  

I've just replaced the following reference:
`NSNotificationCenter.defaultCenter`

To use the ios getter utility:
`utils.ios.getter(NSNotificationCenter, NSNotificationCenter.defaultCenter);`

And everything is working fine on iOS 8.  Should I make a pull request or are you working on this?

**Comment by jaypan** [comment]
It would be nice to get this committed.

**Comment by Daxito** [comment]
+1

**Comment by AntonDobrev** [comment]
Thanks everyone, I have submitted a PR #54 with the fix similar to the approach suggested by @thomasmoon Let me know should you have questions or considerations. 

Awaiting the other contributors to review too.

**Comment by AntonDobrev** [comment]
Fixed in 0.0.18.
