### ISSUE TITLE
The build fails when this plugin is added

### ISSUE THREAD

**Issue by gaurav-chandra** [NativeScript/push-plugin#5]
The package.json lists the following plugins:
```
"dependencies": {
    "nativescript-background-http": "0.0.3",
    "nativescript-clipboard": "^1.1.2",
    "nativescript-dialog": "0.0.5",
    "nativescript-push-notifications": "0.0.11",
    "nativescript-toast": "^1.2.0",
    "tns-core-modules": "1.5.1"
  }
```
When I remove push notification plugin, the build is success else I get the following build errors:
```
:processNativescript-background-httpNativescript-push-notificationsDebugResources FAILED
```

**Comment by AntonDobrev** [comment]
@gaurav-chandra 

Thanks for bringing the issue to our attention. 

The latest release https://github.com/NativeScript/push-plugin/commit/40027ed72d50f167614e8f3fc3933df8de194c78  introduces a lot of improvements.

If the issue persists, can you please provide the whole exception stack and the NS version used?
