### ISSUE TITLE
How to build this plugin locally?

### ISSUE THREAD

**Issue by svzi** [NativeScript/push-plugin#50]
Hi there!

I need to make a modification to the Android source of this plugin, in order to make it useable for our project. The GCM messaging concept describes two types of push messages: notifications and data messages (see https://developers.google.com/cloud-messaging/concept-options for details). For whatever reason, this plugin handles every push message as notification, even if it has only a data property set (and no notification property!). This makes the plugin really useless for data messages, because the app will send a notification message to the notification tray, for every push message it receives while the app is not running. To make it even uglier, the push message contains no message, because there is no message property in the push message from the server (because it's only a data message, no notification).

For that reason I've forked and cloned the repository. I can easily add the necessary adjustments on the Java side, but I'm unable to build a new .jar file from my local version of the plugin. I worked with Java many years, but not with native Android development. So I tried  with intelliJ IDE, as suggested by the README.MD in the android src folder, without luck. I could build the project, but I could not export a JAR file, because I don't know how to do. Also the IDE suggested to migrate to Gradle. I've also tried to import the project into Android Studio from "Eclipse ADT". The import process worked without any issues, but I was unable to build it, because of missing dependencies:

![bildschirmfoto 2016-10-10 um 15 12 03](https://cloud.githubusercontent.com/assets/1890513/19237671/70073a92-8efe-11e6-8a45-f4caec02aaab.png)

I would really love to add the necessary modifications by myself and provide a PR later on, but I need some kind of step-by-step guide on how to build this plugin locally (including the export of the .jar file). Could you please provide it?

Best,
Sven

**Comment by svzi** [comment]
Thanks to the awesome help of @Pip3r4o , I was able to build the project locally yesterday. I needed some help in order to get everything running with Gradle and other stuff. Without Peter, I wouldn't be able to solve the main issue.

I was able to modify the Android source to only display notifications, when the app is not running and the `message` property was set. This way you can use this plugin to receive data messages, without any notification for the end user.

**Comment by AntonDobrev** [comment]
@svzi Thanks for your contribution, will examine the PR later on. Let me know should you have any suggestions or considerations. I am closing the issue now, let me know if you need to reopen it.
