### ISSUE TITLE
TypeError: NSNotificationCenter.defaultCenter is not a function

### ISSUE THREAD

**Issue by terreb** [NativeScript/push-plugin#57]
I get this after upgrading to xCode 8.1:

file:///app/tns_modules/nativescript-push-notifications/push-plugin.js:158:54: JS ERROR TypeError: NSNotificationCenter.defaultCenter is not a function. (In 'NSNotificationCenter.defaultCenter()', 'NSNotificationCenter.defaultCenter' is an instance of NSNotificationCenter)

The plugin versions is 0.0.17

**Comment by AntonDobrev** [comment]
Fixed in 0.0.18
