### ISSUE TITLE
How to launch the app on "click_action" from GCM?

### ISSUE THREAD

**Issue by bradmartin** [NativeScript/push-plugin#6]
I am receiving the notifications fine from GCM. In the payload from GCM, there is a "click_action" property that expects an activity with matching intent (https://developers.google.com/cloud-messaging/http-server-ref#table5). What would this be in a NativeScript app. I've tried passing every action from the sample-push app provided by {N} and the app will not open.

Do I need to add an activity? Thanks.

**Comment by AntonDobrev** [comment]
@bradmartin 

This functionality requires that the app is launched with a custom activity. This said, the support for custom activities should be added in NS. 

Here is the feature request which you can follow https://github.com/NativeScript/android-runtime/issues/88

**Comment by vbresults** [comment]
@alexanderfilipov Can this be re-opened?  Custom activities have been added in NS 1.7.0

**Comment by Daxito** [comment]
+1

**Comment by hvadotnarola** [comment]
Is there any event or flag so that we can determine tha app in foreground/background ?

**Comment by DimitarTachev** [comment]
I'm closing this one as GCM (Google Cloud Messaging) is deprecated by Google and replaced by Firebase Cloud Messaging (FCM) in the Android part of this plugin.

Feel free to open a new issue if you have any problems with the FCM implementation.

**Comment by hackerunet** [comment]
How was this solved implementing FCM?
