### ISSUE TITLE
ERROR TypeError: this._removeObserver is not a function

### ISSUE THREAD

**Issue by Daxito** [NativeScript/push-plugin#61]
Hi,
I am getting this error when using iOS when calling areNotificationsEnabled()

file:///app/tns_modules/nativescript-push-notifications/push-plugin.js:123:41: JS ERROR TypeError: this._removeObserver is not a function. (In 'this._removeObserver(self.areNotificationsEnabledObserver, "areNotificationsEnabled")', 'this._removeObserver' is undefined)

Push Not Ver: 0.0.18
{N}: 2.3

Any idea?

**Comment by Daxito** [comment]
Seems like `this` refers to NotificationObserver and not the pushPluginObject

**Comment by AntonDobrev** [comment]
@Daxito Thanks again, fixed in 0.0.19.

**Comment by Daxito** [comment]
Thank you for your fast response!
I am testing today!
