### ISSUE TITLE
Older API Level Compatibility

### ISSUE THREAD

**Issue by vbresults** [NativeScript/push-plugin#64]
There's a reference to `org.json.JSONArray` which doesn't exist until API Level 19.

I was experiencing strange issues with an unrelated but identical GCM implementation where things wouldn't fire on older API levels (14, 15), this probably was the source of all these problems.

**Comment by AntonDobrev** [comment]
@vbresults In the latest version 0.1.0 we aimed for removing such dependencies. Do not hesitate to report such feedback again. Thank you.
