### ISSUE TITLE
notification.contentView is null in android 7.0

### ISSUE THREAD

**Issue by ralphpig** [NativeScript/push-plugin#66]
NotificationBuild.java:105 
`notification.contentView.setImageViewResource(android.R.id.icon, largeIcon);` returns null in Android 7.0.

I'm not entirely sure why, but it is documented as having this behavior.
[Android Docs](https://developer.android.com/reference/android/app/Notification.html#contentView)

**Comment by ralphpig** [comment]
I found a similar commit that would fix this issue.

https://github.com/EddyVerbruggen/nativescript-local-notifications/commit/bf0aa96632d73183a95e408d317016dedae99ab8

**Comment by AntonDobrev** [comment]
@ralphpig Thanks, this should be resolved in the latest 43bea908aca8a3f4d520a4e2f3cdd419329c0cfd 0.1.0 release.
