### ISSUE TITLE
Compatible with FCM?

### ISSUE THREAD

**Issue by zoeitsolutions** [NativeScript/push-plugin#71]
Hi, since GQM is now being moved over to FCM (firebase), is this plugin currently compatible with FCM?

**Comment by AntonDobrev** [comment]
@zoeitsolutions Robert, the plugin is yet utilizing the GCM client implmentation, but FCM kept a backwards compatibility and it is working with FCM too (for Android only). Full FCM support with the new SDK is to be added in the future in the plugin.

Let me know if you have questions.

**Comment by zoeitsolutions** [comment]
@AntonDobrev thanks. Does this mean if I am wanting to use this plugin on Android, I could create it as a project on FCM and then simply use the FCM values/configs with this plugin?

**Comment by AntonDobrev** [comment]
@zoeitsolutions Yes, Robert. You can add the sender ID in the client push settings, register for push notifications and use the obtained token and FCM server key to send push messages to devices running your app.

**Comment by AntonDobrev** [comment]
@zoeitsolutions Since version 0.1.0 43bea908aca8a3f4d520a4e2f3cdd419329c0cfd the plugin incorporates the FCM SDK. Documentation is available [here](https://github.com/NativeScript/push-plugin#android-configuration-for-using-firebase-cloud-messaging).
