### ISSUE TITLE
Push notification support from azure mobile app(service)

### ISSUE THREAD

**Issue by Habeeb-mohamed** [NativeScript/push-plugin#72]
Right now azure is having framework for iOS,Android,..Cordova. I found a plugin for azure but it doesn't support push notification.
https://github.com/PeterStaev/nativescript-azure-mobile-apps 

How to implement azure push notification service in nativescript?

Thanks in advance.

**Comment by PeterStaev** [comment]
Hey @Habeeb-mohamed , I've just published v1.0 of the azure apps plugin on npm that support push notifications. You can check the readme and sample app on how to use them.
