### ISSUE TITLE
Automatically subscribe to notificationCallbackAndroid on register()

### ISSUE THREAD

**Issue by PeterStaev** [NativeScript/push-plugin#73]
Currently for iOS when in the settings you pass a `notificationCallbackIOS` function, on register the app automatically subscribes to that callback. For Android you have to manually do this by calling `onMessageReceived` in the success callback of the `register` function. This is really not very user-friendly and I think for Android the logic should be changed to match the iOS one, i.e. if the user passes a `notificationCallbackAndroid` in the settings on register the plugin should automatically subscribe to that event.

**Comment by DimitarTachev** [comment]
Hi @PeterStaev,

Thanks for reporting this. The improvement was implemented in Pull Request https://github.com/NativeScript/push-plugin/pull/191 and will be part of the next release of the plugin.
