### ISSUE TITLE
Error on merge resources

### ISSUE THREAD

**Issue by victorhugom** [NativeScript/push-plugin#8]
App does not build and show error when try to merge the resource files inside the project dependency "nativescript-plugin-google-play-services"

```
...
AAPT out(1955802397) : No Delegate set : lost message:  Output file: C:\...App\platforms\android\build\intermediates\res\merged\NativescriptAppResourcesnativescript-facebook-pluginnativescript-google-maps-sdknativescript-plugin-google-play-servicesnativescript-push-notifications\debug\drawable-xxxhdpi\arrow_down.png
AAPT out(359020287) : No Delegate set : lost message:Done
AAPT out(1955802397) : No Delegate set : lost message:Error
AAPT out(1955802397) : No Delegate set : lost message:Done
...
```

**Comment by AntonDobrev** [comment]
@victorhugom 

Thanks for bringing the issue to our attention. 

The latest release https://github.com/NativeScript/push-plugin/commit/40027ed72d50f167614e8f3fc3933df8de194c78  introduces a lot of improvements.

If the issue persists, can you please provide the whole exception stack, the NS version used and the plugins used in the project.

**Comment by rorofino** [comment]
I have the same problem and unfortunately the 0.0.14 did not fix it.

I´m using NS version 1.5.2.

Steps to reproduce the problem:

1) Create new NS project
2) Add platform android
3) install the nativescript-google-maps-sdk (i´using version 1.2.2)
4) install the nativescript-push-notifications (i tried version 0.0.13 and 0.0.14)
5) tns run android

[buildLog.txt](https://github.com/NativeScript/push-plugin/files/119617/buildLog.txt)
[fullBuildLog.txt](https://github.com/NativeScript/push-plugin/files/119628/fullBuildLog.txt)

**Comment by EddyVerbruggen** [comment]
Did you remove and add the android platform from your NS project after updating the plugin? I just tried your steps and it deployed fine.. (I included these plugins as they're in your buildlog: nativescript-facebook-plugin, nativescript-geolocation, nativescript-google-maps-sdk, nativescript-push-notifications)
