### ISSUE TITLE
Issues with Telerik Platform Backend Services

### ISSUE THREAD

**Issue by Daxito** [NativeScript/push-plugin#80]
I just updated the plugin to latest version 0.1.0 and I now I get this error when trying to register with Telerik Platform Services, my code is based on [https://github.com/NativeScript/sample-push-plugin](url), am I missing something? Thanks!

![screenshot_1484080040](https://cloud.githubusercontent.com/assets/16787057/21823624/70e7ab1e-d741-11e6-817d-3b3e58e4790e.png)

**Comment by AntonDobrev** [comment]
@Daxito Thanks for the prompt feedback. This version incorporates the FCM SDK for Android and requires a little bit different setup. I just updated the docs [here](https://github.com/NativeScript/push-plugin#android-configuration-for-using-firebase-cloud-messaging). 

Can you please retry and let me know the results?

**Comment by Daxito** [comment]
@AntonDobrev 

Here are my results after following the steps in the docs, I had to make some other modifications before it actually worked, please see below:

1. From the file App_Resources/Android/app.gradle, I had to remove the line **"compile 'com.google.android.gms:play-services-gcm:+'"** from the dependencies, otherwise I would get the error reported here [https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/163](url).

2. From the file App-Resources/Android/AndroidManifest.xml I had to **remove** all this section:

`
`

Otherwise I would get the error **... Unable to instantiate receiver com.google.android.gms.gcm.GcmReceiver: java.lang.ClassNotFoundException: Didn't find class \"com.google.android.gms.gcm.GcmReceiver\ ...**

3. I had to manually copy the file **google-services.json** from the location under **App_Resources/android** to the location **platform/android**, for some reason it was not being copied over (maybe I missed something?)

4. The argument "data" on onMessageReceived, does not contain a property "foreground" anymore, this is just an FYI, because I was actually using it.

5. Very ofter I execute "tns platform clean android",  so what it means is that now I have to remember I need to modify the **build.gradle** file and add the two lines needed per the documentation, is there a way to automate this? it would be perfect.

Thank you for your help

**Comment by AntonDobrev** [comment]
@Daxito 

I forgot to mention that it would be best to run the following in succession when adding new Android dependencies:

1. Run `tns remove android` 
1. Run `tns add android`
1. Add the plugin
1. Run `tns run android` as you'd normally do

Please note that you need to manually copy the `google-services.json`. 

You may automate the addition with either a hook or a simple script that adds the line in the file. This will also be considered as enhancement for the plugin in next releases. 

Thanks for reporting the foreground issue, will post another issue for it.
