### ISSUE TITLE
Crash when receive notification

### ISSUE THREAD

**Issue by mounirka** [NativeScript/push-plugin#83]
Hi guys, i followed the instruction and when i open the app i can get the token of the id, but when i send the notification from my server, the app crashes with the following error:
`Unable to instantiate receiver com.google.android.gms.gmc.GcmReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.gmc.GcmReceiver" on path: DexPathList`

I have update googe play services from the sdk manager, i don't know what's going on.
Any help is appreciated, thank you.

**Comment by Daxito** [comment]
I think fix is here:
https://github.com/NativeScript/push-plugin/issues/80#issuecomment-272197165

**Comment by mounirka** [comment]
Thank you @Daxito, removing the lines you mentioned from the manifest solved it, well done ;)
