### ISSUE TITLE
Cannot use plugin on IOS

### ISSUE THREAD

**Issue by mounirka** [NativeScript/push-plugin#85]
Hi guys, the plugin is working good on android, but when i try to use it on ios, it gives me an error when i call the require("nativescript-push-plugin"). Here is the output:
```
NativeScript could not load bundle file:///var/containers/Bundle/Application/F5217547-FD52-42C5-9316-52D2613351EB/My.app/Frameworks/PushPlugin.framework
***** Fatal JavaScript exception - application has been terminated. *****
Native stack trace:
1   0x1007f7764 NativeScript::FFICallback<NativeScript::ObjCMethodCallback>::ffiClosureCallback(ffi_cif*, void*, void**, void*)
2   0x1010812cc ffi_closure_SYSV_inner
3   0x1010841b4 .Ldo_closure
4   0x18bf4bd30 <redacted>
5   0x18c0bf880 <redacted>
6   0x18bf4bd30 <redacted>
7   0x18bf4bcb0 <redacted>
8   0x18bf36128 <redacted>
9   0x18bf36290 <redacted>
10  0x18bf4b59c <redacted>
11  0x18bf4b0c4 <redacted>
12  0x18bf46328 <redacted>
13  0x18bf16da0 <redacted>
14  0x18c70075c <redacted>
15  0x18c6fa130 <redacted>
16  0x18600eb5c <redacted>
17  0x18600e4a4 <redacted>
18  0x18600c0a4 <redacted>
19  0x185f3a2b8 CFRunLoopRunSpecific
20  0x1879ee198 GSEventRunModal
21  0x18bf817fc <redacted>
22  0x18bf7c534 UIApplicationMain
23  0x101084044 ffi_call_SYSV
24  0x101080e0c ffi_call_int
25  0x101080924 ffi_call
26  0x1007b94fc NativeScript::FFICall::call(JSC::ExecState*)
27  0x100deb888 JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*)
28  0x100df3f08 llint_entry
29  0x100df3f18 llint_entry
30  0x100ded7f8 vmEntryToJavaScript
31  0x100d8d294 JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*)
JavaScript stack trace:
1   @file:///app/tns_modules/nativescript-push-notifications/push-plugin.js:9:31
2   promiseReactionJob@[native code]
3   require@[native code]
4   onUpload@file:///app/pages/main-page/main-view-model.js:334:
```
Anybody who knows what's going on?
And another question, can i use GCM with IOS? Does i have to add the .plist from the firebase project?

Thank you.

**Comment by mounirka** [comment]
Anyone who have successfully added the plugin to ios can please explain me how he have done it?
Thank you

**Comment by mounirka** [comment]
Come on guys nobody can help? please

**Comment by AntonDobrev** [comment]
@mounirka The plugin should be operating as expected. It does not rely on the FCM implementation for iOS, it is using the generic iOS framework to do so and is designed to communicate with APNs. 

In regard the error - it appears that the plugin is not correctly added or cannot load some of its dependencies. 

I'd suggest that you double check the whole project initialization and adding the plugin to the app. It appears that the iOS platform is not correctly initialized or not updated after the plugin was added.

**Comment by mounirka** [comment]
hi @AntonDobrev  thank you for your reply, so there is no way to make it work with GCM? thank you

**Comment by AntonDobrev** [comment]
@mounirka Yes, the plugin for iOS cannot be used with FCM, but you can use it with any push provider of your choice.

**Comment by mounirka** [comment]
ok thank you, by the way the plugin now is working on ios. Thank you for your help

**Comment by jogboms** [comment]
Then how did you get it to work? @mounirka
