### ISSUE TITLE
How can I get the toke before the register device?

### ISSUE THREAD

**Issue by cbolivar-sts** [NativeScript/push-plugin#86]
Hello,

I would like to know, how can I do to get the Token ID or Device ID after that register device is successful?

My goal is that I need this token because I have a backend service for sending a notification to the specific user on my local database, no broadcast notifications.

Any suggestions?

Thank you!

**Comment by AntonDobrev** [comment]
@cbolivar-sts The register method will receive an argument in the _success_ function that contains the token. 

The device Id can be obtained with using your own functionality for assigning a device Id, using the NS module for this or by using any native functionality exposed by NS. 

I hope this helps.
