### ISSUE TITLE
Android Push Notification payload does not contain "foreground" property anymore

### ISSUE THREAD

**Issue by Daxito** [NativeScript/push-plugin#87]
For Android, Version 0.1.0 of this plugin does not have the property "foreground" anymore, so right now when I receive a notification, there is not way to tell if the app is in the "Foreground" or not, I want to ignore the notification if foreground === true.

**Comment by AntonDobrev** [comment]
@Daxito As agreed in another thread this issue is logged and communicated to the developers. Thanks for your cooperation and patience.

**Comment by Daxito** [comment]
Thank you @AntonDobrev ! I just wanted to isolate this particular issue since it is actually important to fix, I thought at the beginning that it was not a big deal but now I don't have a way to distinguish between notifications received when app is foreground or not.

Thanks!

**Comment by AntonDobrev** [comment]
Added (again) in [0.1.1](https://github.com/NativeScript/push-plugin/commit/ca94e021560c0a7d9bb0db95a703478418e70bf3).
