### ISSUE TITLE
use push plugin in IOS

### ISSUE THREAD

**Issue by mbvcesar** [NativeScript/push-plugin#9]
How can i invoke notificationCallbackIOS and receive notifications?
Using IOS and whithout telerik backend.

**Comment by AntonDobrev** [comment]
@mbvcesar 

You can call the API for registering for push notifications as in the documentation of the plugin. You will obtain a push token that has to be registered with your own push server (in case you do not want to use Telerik Platform). This token should be sent along with a push notification payload to Apple Push Notifications Service (APNs) which will send a push notification to the device. When the app is launched through the notification, the callback will be called. It will be also called when the app is running and the notification is received. 

You can read more in the Apple documentation [here](https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/Chapters/Introduction.html#//apple_ref/doc/uid/TP40008194-CH1-SW1)

More on the iOS development with NativeScript can be read [here](http://docs.nativescript.org/start/getting-started).
