### ISSUE TITLE
Gettings Not Found Errors

### ISSUE THREAD

**Issue by iridiumsoft** [NativeScript/push-plugin#91]
Hi,
I'm trying to use this plugin but having problem when i run the code, I have setup everything according to the instructions given but it looks like missing something. 
Here is what i see when run the code.
`Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.RemoteMessage$Notification" on path: DexPathList[[zip file "/data/app/org.sujag.app-1/base.apk"],nativeLibraryDirectories=[/data/app/org.sujag.app-1/lib/x86, /data/app/org.sujag.app-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]`

**Comment by AntonDobrev** [comment]
@iridiumsoft Can you please specify when this occurs, I am assuming it is at the time of sending a push notification and it is received on the device? Also, what is the payload and the means of sending the push message?

**Comment by iridiumsoft** [comment]
Hi @AntonDobrev Thank you for reply. Its occurs when application run and first activity start, I'm following the instructions from repo README. Here is what i'm doing on my app.component constructor.
`var pushPlugin = require("nativescript-push-notifications");
    var self = this;
    pushPlugin.register({ senderID: '<ENTER_YOUR_PROJECT_NUMBER>' }, function (data){
        self.set("message", "" + JSON.stringify(data));
    }, function() { });

    pushPlugin.onMessageReceived(function callback(data) {
        self.set("message", "" + JSON.stringify(data));
    });`

When this code run the error occurs that I mentioned in my first post.

**Comment by AntonDobrev** [comment]
@iridiumsoft I am afraid that this is not a known issue. Can you please double check the configuration of the plugin as per the docs and if you have installed all the latest Android libraries on the local machine? Also, do not forget to try _tns platform remove android_ and _tns platform add android_ before this. 

Also, what is the version of the device OS, is it happening on all devices running Android?

**Comment by iridiumsoft** [comment]
Finally works for me. I had to clear the node_modules and install them again plus tns prepare android to get it working
