### ISSUE TITLE
File google-services.json is missing. The Google Services Plugin cannot function without it. 

### ISSUE THREAD

**Issue by philippsander** [NativeScript/push-plugin#95]
After adding your plugin I get this message.

Your README says: Since version 0.1.1 thе google-services plugin is added via a hook. You can skip this step for versions 0.1.1 and above.

I'm using ^0.1.1

**Comment by AntonDobrev** [comment]
@philippsander 

The Google Services plugin is added by default via a hook. This said, the hint refers to the first step of the Android configuration. 

As a second step you need to manually add the `google-services.json` file for your project in Firebase. 

Let me know if this helps.

**Comment by philippsander** [comment]
I don't use firebase

**Comment by AntonDobrev** [comment]
@philippsander 

The plugin relies on Firebase for the Android part of the notifications. 

In case you are still using Google Cloud Messaging for Android you can either:

- Migrate the project to Firebase 
- Use a version of the plugin below 0.1.0.

**Comment by philippsander** [comment]
Yes I am forced to use GCM and APNS.

so 0.0.19? is that the highest verison I can use?

**Comment by AntonDobrev** [comment]
@philippsander 

You can use APNs with this plugin, any version. 

As for Android:

- Firebase Cloud Messaging is now succeeding GCM so it may be good for new projects to consider it. 
- 0.0.19 is the latest which does not rely on the Firebase client-side SDK.

**Comment by philippsander** [comment]
thanks for your help!

**Comment by AntonDobrev** [comment]
I am closing the question now. Let me know if further questions arise.
