### ISSUE TITLE
showModal() from Notification click

### ISSUE THREAD

**Issue by philippsander** [NativeScript/push-plugin#99]
Is it possible?

I want to go to a View or open the Modal panel if the users click on a notification.

**Comment by Daxito** [comment]
Everything is possible, when you tap on the notification the App is launched and from there you can do anything.

**Comment by philippsander** [comment]
well I don't have a ViewContainerRef available, which throws an exception.

**Comment by haris008** [comment]
How you solved it @philippsander ? I mean how you are navigating now?

**Comment by philippsander** [comment]
I pass the ViewContainerRef in manually. via a setter
